package br.com.iforce.praxis.shared.notification.model;

public enum InAppNotificationType {
    RESULT_DELIVERY_DLQ,
    MARKETPLACE_ORDER_RECEIVED,
    MARKETPLACE_REVIEW_RECEIVED,
    MARKETPLACE_PAYOUT_RELEASED,
    MARKETPLACE_LISTING_APPROVED,
    MARKETPLACE_LISTING_REJECTED,
    MARKETPLACE_PROFESSIONAL_VERIFIED
}
