package br.com.iforce.praxis.integrity.model;

public enum IntegrityEventType {
    SESSION_STARTED,
    SESSION_RESUMED,
    SESSION_EXPIRED,
    HEARTBEAT,
    TAB_HIDDEN,
    TAB_VISIBLE,
    INPUT_MODE_CHANGED,
    NODE_PRESENTED,
    ASSET_LOADED,
    STIMULUS_STARTED,
    VIDEO_PLAYBACK_STARTED,
    VIDEO_PLAYBACK_PAUSED,
    VIDEO_PLAYBACK_COMPLETED,
    VIDEO_PLAYBACK_ERROR,
    RESPONSE_SELECTED,
    RESPONSE_CONFIRMED,
    SESSION_CLOSED
}
