-- Consolida controles técnicos de privacidade, revisão humana e incidentes.
-- Os documentos jurídicos continuam sujeitos à validação profissional, mas o
-- produto passa a impedir operação real sem configuração mínima por empresa.

ALTER TABLE empresas
    ADD COLUMN privacy_controller_name VARCHAR(180),
    ADD COLUMN privacy_controller_tax_id VARCHAR(40),
    ADD COLUMN privacy_service_email VARCHAR(320),
    ADD COLUMN privacy_service_url VARCHAR(500),
    ADD COLUMN privacy_dpo_contact VARCHAR(320),
    ADD COLUMN privacy_legal_basis VARCHAR(1000),
    ADD COLUMN privacy_retention_days INTEGER,
    ADD COLUMN privacy_notice_version VARCHAR(80),
    ADD COLUMN privacy_notice_hash VARCHAR(64),
    ADD COLUMN health_compliance_approved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN health_compliance_approved_by VARCHAR(120);

ALTER TABLE candidate_attempts
    ADD COLUMN privacy_notice_acknowledged_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN privacy_notice_version VARCHAR(80),
    ADD COLUMN privacy_notice_language VARCHAR(20),
    ADD COLUMN privacy_notice_hash VARCHAR(64),
    ADD COLUMN human_review_completed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN human_reviewed_by VARCHAR(120),
    ADD COLUMN human_review_resolution VARCHAR(2000);

CREATE TABLE data_subject_requests (
    id VARCHAR(36) PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    attempt_id VARCHAR(80) NOT NULL,
    request_type VARCHAR(60) NOT NULL,
    contact VARCHAR(320),
    details VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_user_id VARCHAR(120),
    resolution VARCHAR(2000),
    denial_reason VARCHAR(2000),
    responded_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_data_subject_request_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT fk_data_subject_request_attempt
        FOREIGN KEY (attempt_id) REFERENCES candidate_attempts (id) ON DELETE CASCADE
);

CREATE INDEX idx_data_subject_requests_empresa_status
    ON data_subject_requests (empresa_id, status, due_at);
CREATE INDEX idx_data_subject_requests_attempt
    ON data_subject_requests (attempt_id, requested_at);

CREATE TABLE human_review_requests (
    id VARCHAR(36) PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    attempt_id VARCHAR(80) NOT NULL,
    reason VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_user_id VARCHAR(120),
    resolution VARCHAR(2000),
    resolved_at TIMESTAMP WITH TIME ZONE,
    result_released_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_human_review_request_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT fk_human_review_request_attempt
        FOREIGN KEY (attempt_id) REFERENCES candidate_attempts (id) ON DELETE CASCADE
);

CREATE INDEX idx_human_review_requests_empresa_status
    ON human_review_requests (empresa_id, status, due_at);
CREATE INDEX idx_human_review_requests_attempt
    ON human_review_requests (attempt_id, requested_at);
CREATE INDEX idx_human_review_requests_release
    ON human_review_requests (status, result_released_at, resolved_at);

CREATE TABLE candidate_notice_acceptances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    attempt_id VARCHAR(80) NOT NULL,
    notice_version VARCHAR(80) NOT NULL,
    notice_language VARCHAR(20) NOT NULL,
    notice_hash VARCHAR(64) NOT NULL,
    acknowledged_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_candidate_notice_acceptance_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT fk_candidate_notice_acceptance_attempt
        FOREIGN KEY (attempt_id) REFERENCES candidate_attempts (id) ON DELETE CASCADE,
    CONSTRAINT uk_candidate_notice_acceptance
        UNIQUE (attempt_id, notice_version)
);

CREATE INDEX idx_candidate_notice_acceptances_empresa
    ON candidate_notice_acceptances (empresa_id, acknowledged_at);

CREATE TABLE privacy_incidents (
    id VARCHAR(36) PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    discovered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    description VARCHAR(4000) NOT NULL,
    affected_data VARCHAR(4000),
    affected_subjects_estimate INTEGER,
    risk_assessment VARCHAR(4000),
    owner_user_id VARCHAR(120),
    controller_notified_at TIMESTAMP WITH TIME ZONE,
    anpd_notified_at TIMESTAMP WITH TIME ZONE,
    subjects_notified_at TIMESTAMP WITH TIME ZONE,
    retention_until TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_privacy_incident_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas (id)
);

CREATE INDEX idx_privacy_incidents_empresa_status
    ON privacy_incidents (empresa_id, status, discovered_at);
