CREATE TABLE candidate_integrity_sessions (
    id VARCHAR(36) PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    client_session_id VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    last_heartbeat_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    ip_hash VARCHAR(64),
    user_agent_category VARCHAR(40) NOT NULL,
    input_mode VARCHAR(20) NOT NULL,
    CONSTRAINT fk_integrity_session_attempt
        FOREIGN KEY (candidate_attempt_id) REFERENCES candidate_attempts(id) ON DELETE CASCADE,
    CONSTRAINT ck_integrity_session_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'EXPIRED')),
    CONSTRAINT ck_integrity_session_input_mode
        CHECK (input_mode IN ('POINTER', 'TOUCH', 'KEYBOARD', 'UNKNOWN'))
);

CREATE UNIQUE INDEX uq_integrity_active_attempt
    ON candidate_integrity_sessions(candidate_attempt_id)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_integrity_session_attempt_started
    ON candidate_integrity_sessions(candidate_attempt_id, started_at DESC);

CREATE INDEX ix_integrity_session_empresa_status
    ON candidate_integrity_sessions(empresa_id, status);

CREATE TABLE candidate_integrity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    session_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    input_mode VARCHAR(20),
    visibility_state VARCHAR(20),
    sequence_number BIGINT,
    detail VARCHAR(120),
    CONSTRAINT fk_integrity_event_attempt
        FOREIGN KEY (candidate_attempt_id) REFERENCES candidate_attempts(id) ON DELETE CASCADE,
    CONSTRAINT fk_integrity_event_session
        FOREIGN KEY (session_id) REFERENCES candidate_integrity_sessions(id) ON DELETE CASCADE,
    CONSTRAINT ck_integrity_event_input_mode
        CHECK (input_mode IS NULL OR input_mode IN ('POINTER', 'TOUCH', 'KEYBOARD', 'UNKNOWN')),
    CONSTRAINT ck_integrity_event_visibility
        CHECK (visibility_state IS NULL OR visibility_state IN ('VISIBLE', 'HIDDEN'))
);

CREATE UNIQUE INDEX uq_integrity_event_sequence
    ON candidate_integrity_events(session_id, sequence_number)
    WHERE sequence_number IS NOT NULL;

CREATE INDEX ix_integrity_event_attempt_occurred
    ON candidate_integrity_events(candidate_attempt_id, occurred_at);

COMMENT ON TABLE candidate_integrity_sessions IS
    'Sessões técnicas da aplicação, separadas das respostas e da pontuação da avaliação.';

COMMENT ON TABLE candidate_integrity_events IS
    'Telemetria técnica explicável da execução; não altera score nem decide sobre o candidato.';

COMMENT ON COLUMN candidate_integrity_sessions.ip_hash IS
    'Hash HMAC do endereço de rede. O endereço bruto não é persistido.';