CREATE TABLE candidate_integrity_reviews (
    id VARCHAR(36) PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    candidate_attempt_id VARCHAR(80) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    decision VARCHAR(50),
    justification VARCHAR(2000),
    share_with_company BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed_by VARCHAR(120),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    retention_until TIMESTAMPTZ NOT NULL,
    evidence_discarded_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_integrity_review_attempt
        FOREIGN KEY (candidate_attempt_id) REFERENCES candidate_attempts(id) ON DELETE CASCADE,
    CONSTRAINT ck_integrity_review_status
        CHECK (status IN ('PENDING', 'DECIDED')),
    CONSTRAINT ck_integrity_review_decision
        CHECK (decision IS NULL OR decision IN (
            'NO_IMPACT',
            'TECHNICAL_ISSUE_CONFIRMED',
            'REAPPLICATION_RECOMMENDED',
            'PRIVACY_COMPLIANCE_REVIEW'
        )),
    CONSTRAINT ck_integrity_review_decided
        CHECK (
            (status = 'PENDING' AND decision IS NULL AND justification IS NULL AND reviewed_by IS NULL AND decided_at IS NULL)
            OR
            (status = 'DECIDED' AND decision IS NOT NULL AND justification IS NOT NULL AND reviewed_by IS NOT NULL AND decided_at IS NOT NULL)
        )
);

CREATE INDEX ix_integrity_review_empresa_updated
    ON candidate_integrity_reviews(empresa_id, updated_at DESC);

CREATE INDEX ix_integrity_review_retention
    ON candidate_integrity_reviews(empresa_id, retention_until)
    WHERE evidence_discarded_at IS NULL;

CREATE TABLE candidate_integrity_review_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    review_id VARCHAR(36) NOT NULL,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    action VARCHAR(40) NOT NULL,
    actor_user_id VARCHAR(120) NOT NULL,
    details VARCHAR(4000),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_integrity_review_audit_review
        FOREIGN KEY (review_id) REFERENCES candidate_integrity_reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_integrity_review_audit_attempt
        FOREIGN KEY (candidate_attempt_id) REFERENCES candidate_attempts(id) ON DELETE CASCADE,
    CONSTRAINT ck_integrity_review_audit_action
        CHECK (action IN ('QUEUE_CREATED', 'EVIDENCE_ACCESSED', 'DECISION_RECORDED', 'EVIDENCE_DISCARDED'))
);

CREATE INDEX ix_integrity_review_audit_attempt_created
    ON candidate_integrity_review_audit(empresa_id, candidate_attempt_id, created_at);

COMMENT ON TABLE candidate_integrity_reviews IS
    'Fila de revisão humana de evidências técnicas, isolada da pontuação e da decisão de contratação.';

COMMENT ON TABLE candidate_integrity_review_audit IS
    'Trilha append-only de criação, acessos, pareceres e descarte das evidências técnicas.';
