CREATE TABLE tenants (
    id VARCHAR(120) PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    company_id VARCHAR(120) NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    name VARCHAR(180) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    CONSTRAINT fk_users_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_user_tenant_email
        UNIQUE (tenant_id, email)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(80) NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_user_role
        UNIQUE (user_id, role)
);

CREATE INDEX idx_users_email
    ON users (email);
