-- Catalogos configuraveis por tenant (competencias, senioridade, checklist de
-- linguagem, usos do resultado e limites de tempo de resposta).
-- Quando um tenant nao possui linhas para um tipo, o backend devolve os padroes
-- embutidos, preservando o comportamento atual sem necessidade de seed.
-- Compativel com PostgreSQL (prod) e H2 em modo PostgreSQL (testes).

CREATE TABLE tenant_config_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    config_type VARCHAR(40) NOT NULL,
    option_value VARCHAR(200) NOT NULL,
    option_label VARCHAR(200) NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    selected_by_default BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_tenant_config_options_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id),
    CONSTRAINT uk_tenant_config_option
        UNIQUE (tenant_id, config_type, option_value)
);

CREATE INDEX idx_tenant_config_options_lookup
    ON tenant_config_options (tenant_id, config_type, display_order);
