-- Tabela de eventos para Outbox Pattern
-- Permite garantir que eventos sejam entregues de forma confiável
-- Desacopla a lógica de persistência da lógica de entrega

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(120) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Índice otimizado para buscar eventos prontos para processamento
CREATE INDEX idx_outbox_pending ON outbox_events (status, next_attempt_at, tenant_id);

-- Índice para buscar por tipo de evento
CREATE INDEX idx_outbox_event_type ON outbox_events (event_type, tenant_id);

-- Índice para histórico por agregado
CREATE INDEX idx_outbox_aggregate ON outbox_events (aggregate_type, aggregate_id, tenant_id);
