CREATE TABLE candidate_attempts (
    id VARCHAR(80) PRIMARY KEY,
    result_id VARCHAR(80) NOT NULL UNIQUE,
    simulation_id VARCHAR(120) NOT NULL,
    idempotency_key VARCHAR(300) NOT NULL UNIQUE,
    candidate_name VARCHAR(160) NOT NULL,
    candidate_email VARCHAR(180) NOT NULL,
    status VARCHAR(40) NOT NULL,
    score INTEGER,
    decision VARCHAR(60) NOT NULL,
    human_review_required BOOLEAN NOT NULL,
    company_result_string VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE attempt_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    node_id VARCHAR(120) NOT NULL,
    option_id VARCHAR(120) NOT NULL,
    answered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attempt_answers_candidate_attempt
        FOREIGN KEY (candidate_attempt_id)
        REFERENCES candidate_attempts (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_attempt_answer_node
        UNIQUE (candidate_attempt_id, node_id)
);

CREATE TABLE result_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    name VARCHAR(140) NOT NULL,
    score INTEGER NOT NULL,
    tier VARCHAR(40) NOT NULL,
    CONSTRAINT fk_result_items_candidate_attempt
        FOREIGN KEY (candidate_attempt_id)
        REFERENCES candidate_attempts (id)
        ON DELETE CASCADE
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(120) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    message VARCHAR(600) NOT NULL,
    metadata VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_attempt_answers_candidate_attempt_id
    ON attempt_answers (candidate_attempt_id);

CREATE INDEX idx_result_items_candidate_attempt_id
    ON result_items (candidate_attempt_id);

CREATE INDEX idx_audit_events_aggregate
    ON audit_events (aggregate_type, aggregate_id, created_at);
