CREATE TABLE in_app_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    type VARCHAR(80) NOT NULL,
    title VARCHAR(180) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    candidate_name VARCHAR(160) NOT NULL,
    candidate_email VARCHAR(180) NOT NULL,
    outbox_event_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notifications_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_outbox_event
        FOREIGN KEY (outbox_event_id)
        REFERENCES outbox_events (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_notification_dlq_recipient
        UNIQUE (tenant_id, outbox_event_id, recipient_user_id, type)
);

CREATE INDEX idx_notifications_tenant_created
    ON in_app_notifications (tenant_id, created_at DESC);
