CREATE TABLE simulations (
    id VARCHAR(120) PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE simulation_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_id VARCHAR(120) NOT NULL,
    version_number INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL,
    root_node_id VARCHAR(120) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_simulation_versions_simulation
        FOREIGN KEY (simulation_id)
        REFERENCES simulations (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_simulation_version_number
        UNIQUE (simulation_id, version_number)
);

CREATE TABLE simulation_competencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_version_id BIGINT NOT NULL,
    name VARCHAR(140) NOT NULL,
    CONSTRAINT fk_simulation_competencies_version
        FOREIGN KEY (simulation_version_id)
        REFERENCES simulation_versions (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_simulation_competency
        UNIQUE (simulation_version_id, name)
);

CREATE TABLE simulation_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_version_id BIGINT NOT NULL,
    node_id VARCHAR(120) NOT NULL,
    turn_index INTEGER NOT NULL,
    speaker VARCHAR(120) NOT NULL,
    message VARCHAR(1200) NOT NULL,
    time_limit_seconds INTEGER,
    CONSTRAINT fk_simulation_nodes_version
        FOREIGN KEY (simulation_version_id)
        REFERENCES simulation_versions (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_simulation_node
        UNIQUE (simulation_version_id, node_id)
);

CREATE TABLE simulation_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_node_id BIGINT NOT NULL,
    option_id VARCHAR(120) NOT NULL,
    text VARCHAR(800) NOT NULL,
    next_node_id VARCHAR(120),
    critical BOOLEAN NOT NULL,
    audit_note VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_simulation_options_node
        FOREIGN KEY (simulation_node_id)
        REFERENCES simulation_nodes (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_simulation_option
        UNIQUE (simulation_node_id, option_id)
);

CREATE TABLE option_competency_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_option_id BIGINT NOT NULL,
    competency_name VARCHAR(140) NOT NULL,
    score INTEGER NOT NULL,
    CONSTRAINT fk_option_competency_scores_option
        FOREIGN KEY (simulation_option_id)
        REFERENCES simulation_options (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_option_competency_score
        UNIQUE (simulation_option_id, competency_name)
);

CREATE INDEX idx_simulation_versions_status
    ON simulation_versions (status, published_at);

CREATE INDEX idx_simulation_nodes_version
    ON simulation_nodes (simulation_version_id);

CREATE INDEX idx_simulation_options_node
    ON simulation_options (simulation_node_id);

CREATE INDEX idx_option_competency_scores_option
    ON option_competency_scores (simulation_option_id);

