ALTER TABLE simulation_nodes
    ADD COLUMN position_x DOUBLE PRECISION,
    ADD COLUMN position_y DOUBLE PRECISION,
    ADD COLUMN is_final BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN report_text VARCHAR(2000);
