-- Aceite de termos pelo recrutador (REQ-L5): registra quem aceitou, quando e a versão do termo.
-- Insert-only por design — cada aceite é um registro novo; o estado atual é o mais recente.

CREATE TABLE term_acceptances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    term_type VARCHAR(80) NOT NULL,
    term_version VARCHAR(40) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_term_acceptances_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_term_acceptances_lookup
    ON term_acceptances (tenant_id, user_id, term_type);
