ALTER TABLE attempt_answers
    ADD COLUMN received_at TIMESTAMP WITH TIME ZONE;

UPDATE attempt_answers
SET received_at = answered_at
WHERE received_at IS NULL;

ALTER TABLE attempt_answers
    ALTER COLUMN received_at SET NOT NULL;

CREATE TABLE attempt_node_serves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_attempt_id VARCHAR(80) NOT NULL,
    node_id VARCHAR(120) NOT NULL,
    served_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attempt_node_serves_candidate_attempt
        FOREIGN KEY (candidate_attempt_id)
        REFERENCES candidate_attempts (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_attempt_node_serve
        UNIQUE (candidate_attempt_id, node_id)
);

CREATE INDEX idx_attempt_node_serves_candidate_attempt_id
    ON attempt_node_serves (candidate_attempt_id);
