-- Parte B — cobrança Mercado Pago.
-- Entidades financeiras: planos, eventos (append-only), saldo e ledger de créditos,
-- assinaturas recorrentes e recibos de webhook (idempotência).

CREATE TABLE IF NOT EXISTS subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    plan_type VARCHAR(40) NOT NULL,
    price_cents BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'BRL',
    credit_amount INTEGER,
    mp_preapproval_plan_id VARCHAR(120),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_billing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    mp_resource_type VARCHAR(40),
    mp_resource_id VARCHAR(120),
    external_reference VARCHAR(200),
    mp_status VARCHAR(60),
    amount_cents BIGINT,
    currency VARCHAR(8),
    request_id VARCHAR(120),
    raw_payload VARCHAR(8000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_billing_events_tenant ON tenant_billing_events (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS tenant_credit_balances (
    tenant_id VARCHAR(120) PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_credit_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    delta INTEGER NOT NULL,
    reason VARCHAR(40) NOT NULL,
    balance_after INTEGER NOT NULL,
    attempt_id VARCHAR(80),
    billing_event_id BIGINT,
    note VARCHAR(300),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_credit_ledger_tenant ON tenant_credit_ledger (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_credit_ledger_attempt ON tenant_credit_ledger (attempt_id);

CREATE TABLE IF NOT EXISTS tenant_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    plan_id BIGINT,
    mp_preapproval_id VARCHAR(120) UNIQUE,
    status VARCHAR(40) NOT NULL,
    init_point VARCHAR(600),
    current_period_end TIMESTAMP WITH TIME ZONE,
    last_payment_at TIMESTAMP WITH TIME ZONE,
    grace_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON tenant_subscriptions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON tenant_subscriptions (status);

CREATE TABLE IF NOT EXISTS mp_webhook_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id VARCHAR(200) NOT NULL UNIQUE,
    topic VARCHAR(60),
    resource_id VARCHAR(120),
    request_id VARCHAR(120),
    raw_payload VARCHAR(8000),
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Planos iniciais de exemplo (podem ser ajustados pela operação).
INSERT INTO subscription_plans (code, name, plan_type, price_cents, currency, credit_amount, active, created_at)
SELECT 'AVULSO_100', 'Pacote 100 avaliações', 'AVULSO', 49900, 'BRL', 100, TRUE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM subscription_plans WHERE code = 'AVULSO_100');

INSERT INTO subscription_plans (code, name, plan_type, price_cents, currency, credit_amount, active, created_at)
SELECT 'PRO_MENSAL', 'Profissional mensal', 'PROFISSIONAL', 29900, 'BRL', NULL, TRUE, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM subscription_plans WHERE code = 'PRO_MENSAL');
