-- Jornada de Avaliação — agrupa simulações publicadas em sequências de execução.
-- Camada de orquestração acima de simulations/simulation_versions: não substitui
-- nenhuma entidade existente, apenas reaproveita testes já publicados.
-- Multi-empresa: toda tabela carrega empresa_id e os índices garantem isolamento.

CREATE TABLE IF NOT EXISTS assessment_journeys (
    id VARCHAR(120) PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_assessment_journeys_tenant
    ON assessment_journeys (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS assessment_journey_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    journey_id VARCHAR(120) NOT NULL REFERENCES assessment_journeys (id) ON DELETE CASCADE,
    simulation_id VARCHAR(120) NOT NULL,
    simulation_version_number INTEGER NOT NULL,
    sequence_key VARCHAR(80) NOT NULL,
    order_index INTEGER NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_journey_steps_tenant
    ON assessment_journey_steps (tenant_id);
-- Não pode haver ordem duplicada dentro da mesma sequência de uma jornada.
-- Este índice único também serve as consultas por (journey_id, sequence_key, order_index).
CREATE UNIQUE INDEX IF NOT EXISTS uk_journey_step_order
    ON assessment_journey_steps (journey_id, sequence_key, order_index);

CREATE TABLE IF NOT EXISTS assessment_journey_attempts (
    id VARCHAR(80) PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    journey_id VARCHAR(120) NOT NULL,
    candidate_name VARCHAR(160) NOT NULL,
    candidate_email VARCHAR(180) NOT NULL,
    sequence_key VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_journey_attempts_tenant
    ON assessment_journey_attempts (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_journey_attempts_journey
    ON assessment_journey_attempts (journey_id);

CREATE TABLE IF NOT EXISTS assessment_journey_attempt_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL,
    journey_attempt_id VARCHAR(80) NOT NULL REFERENCES assessment_journey_attempts (id) ON DELETE CASCADE,
    journey_step_id BIGINT NOT NULL,
    simulation_id VARCHAR(120) NOT NULL,
    simulation_version_number INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    candidate_attempt_id VARCHAR(80),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_journey_attempt_steps_attempt
    ON assessment_journey_attempt_steps (journey_attempt_id, order_index);
CREATE INDEX IF NOT EXISTS idx_journey_attempt_steps_tenant
    ON assessment_journey_attempt_steps (tenant_id);
