-- Profissionais de psicometria do marketplace.
-- O profissional reaproveita o login da plataforma (UserEntity vinculado à empresa 'PLATFORM'
-- com role PROFISSIONAL); esta tabela guarda os dados específicos do marketplace.

CREATE TABLE marketplace_professionals (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL,
    display_name              VARCHAR(150) NOT NULL,
    document                  VARCHAR(20) NOT NULL,            -- CPF ou CNPJ (apenas dígitos)
    professional_registration VARCHAR(50),                     -- CRP, por exemplo (opcional)
    bio                       TEXT,
    linkedin_url              VARCHAR(300),
    pix_key                   VARCHAR(150),
    mp_seller_id              VARCHAR(100),                    -- id do vendedor no Mercado Pago (OAuth)
    mp_access_token           TEXT,                            -- criptografado em repouso
    verification_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    average_rating            NUMERIC(3,2) DEFAULT 0,
    total_reviews             INTEGER NOT NULL DEFAULT 0,
    total_sales               INTEGER NOT NULL DEFAULT 0,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_professionals_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX uq_marketplace_professionals_user
    ON marketplace_professionals (user_id);
CREATE UNIQUE INDEX uq_marketplace_professionals_document
    ON marketplace_professionals (document);

CREATE TABLE marketplace_professional_specialties (
    professional_id BIGINT NOT NULL,
    specialty       VARCHAR(60) NOT NULL,
    CONSTRAINT fk_marketplace_professional_specialties_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_marketplace_professional_specialty
        UNIQUE (professional_id, specialty)
);
