-- Anúncios (listings) de testes à venda no marketplace.
-- Referenciam uma versão de simulação já existente (conteúdo calibrado) em vez de duplicar o
-- domínio de simulação. Tipos das FKs seguem o schema real: simulations.id é VARCHAR(120) e
-- simulation_versions.id é BIGINT.

CREATE TABLE marketplace_listings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id      BIGINT NOT NULL,
    source_simulation_id VARCHAR(120) NOT NULL,
    source_version_id    BIGINT NOT NULL,
    title                VARCHAR(150) NOT NULL,
    description          TEXT NOT NULL,
    category             VARCHAR(60) NOT NULL,    -- SELECAO, TREINAMENTO, COMPLIANCE, EDUCACAO, LIDERANCA, ATENDIMENTO
    price_cents          BIGINT NOT NULL,
    status               VARCHAR(30) NOT NULL DEFAULT 'DRAFT', -- DRAFT, PENDING_REVIEW, APPROVED, REJECTED, SUSPENDED
    rejection_reason     TEXT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_listings_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id),
    CONSTRAINT fk_marketplace_listings_simulation
        FOREIGN KEY (source_simulation_id) REFERENCES simulations (id),
    CONSTRAINT fk_marketplace_listings_version
        FOREIGN KEY (source_version_id) REFERENCES simulation_versions (id)
);

CREATE INDEX idx_marketplace_listings_status ON marketplace_listings (status);
CREATE INDEX idx_marketplace_listings_category ON marketplace_listings (category);
CREATE INDEX idx_marketplace_listings_professional ON marketplace_listings (professional_id);

CREATE TABLE marketplace_listing_preview_nodes (
    listing_id BIGINT NOT NULL,
    node_id    BIGINT NOT NULL,                   -- PK de simulation_nodes liberado para preview
    CONSTRAINT fk_marketplace_listing_preview_nodes_listing
        FOREIGN KEY (listing_id) REFERENCES marketplace_listings (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_marketplace_listing_preview_node
        UNIQUE (listing_id, node_id)
);
