CREATE TABLE marketplace_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    buyer_tenant_id VARCHAR(120) NOT NULL,
    professional_id BIGINT NOT NULL,
    price_cents BIGINT NOT NULL,
    platform_fee_cents BIGINT NOT NULL,
    professional_payout_cents BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
    mp_preference_id VARCHAR(100),
    mp_payment_id VARCHAR(100),
    cloned_simulation_id VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    paid_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_marketplace_orders_listing
        FOREIGN KEY (listing_id) REFERENCES marketplace_listings (id),
    CONSTRAINT fk_marketplace_orders_buyer
        FOREIGN KEY (buyer_tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_marketplace_orders_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id),
    CONSTRAINT fk_marketplace_orders_cloned_simulation
        FOREIGN KEY (cloned_simulation_id) REFERENCES simulations (id),
    CONSTRAINT ck_marketplace_orders_amounts_non_negative
        CHECK (price_cents >= 0 AND platform_fee_cents >= 0 AND professional_payout_cents >= 0)
);

CREATE INDEX idx_marketplace_orders_buyer ON marketplace_orders (buyer_tenant_id);
CREATE INDEX idx_marketplace_orders_professional ON marketplace_orders (professional_id);
CREATE INDEX idx_marketplace_orders_status ON marketplace_orders (status);
CREATE INDEX idx_marketplace_orders_mp_payment ON marketplace_orders (mp_payment_id);
