CREATE TABLE marketplace_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    amount_cents BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ESCROW',
    escrow_release_at TIMESTAMP WITH TIME ZONE NOT NULL,
    released_at TIMESTAMP WITH TIME ZONE,
    mp_transfer_id VARCHAR(100),
    failure_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_payouts_order
        FOREIGN KEY (order_id) REFERENCES marketplace_orders (id),
    CONSTRAINT fk_marketplace_payouts_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id),
    CONSTRAINT ck_marketplace_payouts_amount_non_negative
        CHECK (amount_cents >= 0)
);

CREATE INDEX idx_marketplace_payouts_professional ON marketplace_payouts (professional_id);
CREATE INDEX idx_marketplace_payouts_status_release
    ON marketplace_payouts (status, escrow_release_at);
