CREATE TABLE marketplace_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    reviewer_tenant_id VARCHAR(120) NOT NULL,
    rating SMALLINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_reviews_order
        FOREIGN KEY (order_id) REFERENCES marketplace_orders (id),
    CONSTRAINT fk_marketplace_reviews_listing
        FOREIGN KEY (listing_id) REFERENCES marketplace_listings (id),
    CONSTRAINT fk_marketplace_reviews_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id),
    CONSTRAINT fk_marketplace_reviews_tenant
        FOREIGN KEY (reviewer_tenant_id) REFERENCES tenants (id),
    CONSTRAINT uk_marketplace_reviews_order UNIQUE (order_id),
    CONSTRAINT ck_marketplace_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_marketplace_reviews_listing ON marketplace_reviews (listing_id);
CREATE INDEX idx_marketplace_reviews_professional ON marketplace_reviews (professional_id);
