CREATE TABLE marketplace_message_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    requester_tenant_id VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_message_threads_listing
        FOREIGN KEY (listing_id) REFERENCES marketplace_listings (id),
    CONSTRAINT fk_marketplace_message_threads_professional
        FOREIGN KEY (professional_id) REFERENCES marketplace_professionals (id),
    CONSTRAINT fk_marketplace_message_threads_tenant
        FOREIGN KEY (requester_tenant_id) REFERENCES tenants (id),
    CONSTRAINT uq_thread_listing_requester UNIQUE (listing_id, requester_tenant_id)
);

CREATE TABLE marketplace_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    sender_type VARCHAR(20) NOT NULL,
    sender_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_marketplace_messages_thread
        FOREIGN KEY (thread_id) REFERENCES marketplace_message_threads (id),
    CONSTRAINT ck_marketplace_messages_sender_type
        CHECK (sender_type IN ('PROFESSIONAL', 'TENANT'))
);

CREATE INDEX idx_marketplace_messages_thread_created
    ON marketplace_messages (thread_id, created_at);
