CREATE TABLE IF NOT EXISTS empresa_plan_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id VARCHAR(120) NOT NULL,
    request_type VARCHAR(40) NOT NULL,
    current_plan VARCHAR(40) NOT NULL,
    requested_plan VARCHAR(40),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_plan_change_requests_empresa
    ON empresa_plan_change_requests (empresa_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_plan_change_requests_status
    ON empresa_plan_change_requests (status, created_at ASC);
