package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/**
 * Padroniza a rastreabilidade de todas as tabelas de negócio existentes.
 *
 * <p>A migration adiciona os campos de criação e alteração em qualquer tabela
 * que ainda não os possua. No PostgreSQL, também instala gatilhos para preencher
 * esses campos e registrar INSERT, UPDATE e DELETE em uma trilha append-only.</p>
 */
public class V1011__universal_table_auditing extends BaseJavaMigration {

    private static final String HISTORY_TABLE = "data_change_history";
    private static final String FLYWAY_TABLE = "flyway_schema_history";
    private static final String CREATED_AT = "created_at";
    private static final String CREATED_BY = "created_by";
    private static final String UPDATED_AT = "updated_at";
    private static final String UPDATED_BY = "updated_by";

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        String schema = resolveCurrentSchema(connection);
        String quote = resolveIdentifierQuote(connection);

        createHistoryTable(connection, schema, quote);

        List<TableReference> tables = loadApplicationTables(connection, schema);
        for (TableReference table : tables) {
            ensureAuditColumns(connection, table, quote);
        }

        if (isPostgreSql(connection)) {
            installPostgreSqlInfrastructure(connection, schema, tables, quote);
        }
    }

    private void createHistoryTable(Connection connection, String schema, String quote) throws SQLException {
        String historyTable = qualifiedName(schema, HISTORY_TABLE, quote);
        execute(connection, """
                CREATE TABLE IF NOT EXISTS %s (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    table_schema VARCHAR(120) NOT NULL,
                    table_name VARCHAR(120) NOT NULL,
                    record_id VARCHAR(1000) NOT NULL,
                    operation VARCHAR(10) NOT NULL,
                    actor_user_id VARCHAR(120) NOT NULL,
                    request_id VARCHAR(120),
                    changed_fields TEXT NOT NULL,
                    old_data TEXT,
                    new_data TEXT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    created_by VARCHAR(120) NOT NULL DEFAULT 'SYSTEM',
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_by VARCHAR(120) NOT NULL DEFAULT 'SYSTEM',
                    CONSTRAINT ck_data_change_history_operation
                        CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
                )
                """.formatted(historyTable));

        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_data_change_history_record
                    ON %s (table_schema, table_name, record_id, created_at)
                """.formatted(historyTable));
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_data_change_history_actor
                    ON %s (actor_user_id, created_at)
                """.formatted(historyTable));
        execute(connection, """
                CREATE INDEX IF NOT EXISTS idx_data_change_history_request
                    ON %s (request_id)
                """.formatted(historyTable));
    }

    private List<TableReference> loadApplicationTables(Connection connection, String schema) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        List<TableReference> tables = new ArrayList<>();

        try (ResultSet resultSet = metadata.getTables(
                connection.getCatalog(),
                schema,
                "%",
                new String[]{"TABLE"}
        )) {
            while (resultSet.next()) {
                String tableSchema = resultSet.getString("TABLE_SCHEM");
                String tableName = resultSet.getString("TABLE_NAME");
                if (tableSchema == null || tableName == null || !tableSchema.equalsIgnoreCase(schema)) {
                    continue;
                }
                if (FLYWAY_TABLE.equalsIgnoreCase(tableName)) {
                    continue;
                }
                tables.add(new TableReference(tableSchema, tableName));
            }
        }

        tables.sort(Comparator.comparing(TableReference::name));
        return tables;
    }

    private void ensureAuditColumns(
            Connection connection,
            TableReference table,
            String quote
    ) throws SQLException {
        Set<String> columns = loadColumns(connection, table);
        String qualifiedTable = qualifiedName(table.schema(), table.name(), quote);

        addColumnWhenMissing(
                connection,
                columns,
                qualifiedTable,
                CREATED_AT,
                "TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP"
        );
        addColumnWhenMissing(
                connection,
                columns,
                qualifiedTable,
                CREATED_BY,
                "VARCHAR(120) NOT NULL DEFAULT 'SYSTEM_MIGRATION'"
        );
        addColumnWhenMissing(
                connection,
                columns,
                qualifiedTable,
                UPDATED_AT,
                "TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP"
        );
        addColumnWhenMissing(
                connection,
                columns,
                qualifiedTable,
                UPDATED_BY,
                "VARCHAR(120) NOT NULL DEFAULT 'SYSTEM_MIGRATION'"
        );
    }

    private Set<String> loadColumns(Connection connection, TableReference table) throws SQLException {
        Set<String> columns = new HashSet<>();
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet resultSet = metadata.getColumns(
                connection.getCatalog(),
                table.schema(),
                table.name(),
                "%"
        )) {
            while (resultSet.next()) {
                String columnName = resultSet.getString("COLUMN_NAME");
                if (columnName != null) {
                    columns.add(columnName.toLowerCase(Locale.ROOT));
                }
            }
        }
        return columns;
    }

    private void addColumnWhenMissing(
            Connection connection,
            Set<String> columns,
            String qualifiedTable,
            String columnName,
            String definition
    ) throws SQLException {
        if (columns.contains(columnName)) {
            return;
        }
        execute(connection, "ALTER TABLE " + qualifiedTable + " ADD COLUMN " + columnName + " " + definition);
        columns.add(columnName);
    }

    private void installPostgreSqlInfrastructure(
            Connection connection,
            String schema,
            List<TableReference> tables,
            String quote
    ) throws SQLException {
        String applyFunction = qualifiedName(schema, "praxis_apply_audit_columns", quote);
        String redactFunction = qualifiedName(schema, "praxis_redact_audit_json", quote);
        String captureFunction = qualifiedName(schema, "praxis_capture_row_history", quote);
        String protectFunction = qualifiedName(schema, "praxis_prevent_history_mutation", quote);
        String historyTable = qualifiedName(schema, HISTORY_TABLE, quote);

        execute(connection, createApplyAuditColumnsFunction(applyFunction));
        execute(connection, createRedactionFunction(redactFunction));
        execute(connection, createCaptureHistoryFunction(
                captureFunction,
                redactFunction,
                historyTable
        ));
        execute(connection, createProtectHistoryFunction(protectFunction));

        for (TableReference table : tables) {
            if (HISTORY_TABLE.equalsIgnoreCase(table.name())) {
                continue;
            }
            installTableTriggers(connection, table, quote, applyFunction, captureFunction);
        }

        execute(connection, "DROP TRIGGER IF EXISTS trg_praxis_history_append_only ON " + historyTable);
        execute(connection, """
                CREATE TRIGGER trg_praxis_history_append_only
                BEFORE UPDATE OR DELETE ON %s
                FOR EACH ROW
                EXECUTE FUNCTION %s()
                """.formatted(historyTable, protectFunction));
    }

    private String createApplyAuditColumnsFunction(String functionName) {
        return """
                CREATE OR REPLACE FUNCTION %s()
                RETURNS trigger AS $$
                DECLARE
                    resolved_actor VARCHAR(120);
                BEGIN
                    resolved_actor := LEFT(
                        COALESCE(
                            NULLIF(current_setting('praxis.actor_user_id', true), ''),
                            current_user,
                            'SYSTEM'
                        ),
                        120
                    );

                    IF TG_OP = 'INSERT' THEN
                        NEW.created_at := COALESCE(NEW.created_at, CURRENT_TIMESTAMP);
                        IF NEW.created_by IS NULL
                            OR BTRIM(NEW.created_by) = ''
                            OR NEW.created_by IN ('SYSTEM', 'SYSTEM_MIGRATION') THEN
                            NEW.created_by := resolved_actor;
                        END IF;

                        NEW.updated_at := COALESCE(NEW.updated_at, NEW.created_at, CURRENT_TIMESTAMP);
                        IF NEW.updated_by IS NULL
                            OR BTRIM(NEW.updated_by) = ''
                            OR NEW.updated_by IN ('SYSTEM', 'SYSTEM_MIGRATION') THEN
                            NEW.updated_by := NEW.created_by;
                        END IF;
                        RETURN NEW;
                    END IF;

                    NEW.created_at := OLD.created_at;
                    NEW.created_by := OLD.created_by;
                    NEW.updated_at := CURRENT_TIMESTAMP;
                    NEW.updated_by := resolved_actor;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql
                """.formatted(functionName);
    }

    private String createRedactionFunction(String functionName) {
        return """
                CREATE OR REPLACE FUNCTION %s(payload JSONB)
                RETURNS JSONB AS $$
                DECLARE
                    sanitized JSONB := payload;
                    field_name TEXT;
                BEGIN
                    IF payload IS NULL THEN
                        RETURN NULL;
                    END IF;

                    FOR field_name IN SELECT jsonb_object_keys(payload)
                    LOOP
                        IF field_name ~* '(password|secret|token|credential|authorization|cookie|raw_payload|payload|email|name|phone|tax_id|cpf|cnpj|address|candidate|company_result_string|settings|metadata|description|message|note|text)' THEN
                            sanitized := jsonb_set(
                                sanitized,
                                ARRAY[field_name],
                                to_jsonb('[REDACTED]'::TEXT),
                                false
                            );
                        END IF;
                    END LOOP;

                    RETURN sanitized;
                END;
                $$ LANGUAGE plpgsql IMMUTABLE
                """.formatted(functionName);
    }

    private String createCaptureHistoryFunction(
            String functionName,
            String redactFunction,
            String historyTable
    ) {
        return """
                CREATE OR REPLACE FUNCTION %s()
                RETURNS trigger AS $$
                DECLARE
                    old_row JSONB;
                    new_row JSONB;
                    source_row JSONB;
                    primary_key_columns TEXT[];
                    primary_key_column TEXT;
                    record_key JSONB := '{}'::JSONB;
                    changed_fields_json JSONB;
                    resolved_actor VARCHAR(120);
                    resolved_request_id VARCHAR(120);
                BEGIN
                    IF TG_OP IN ('UPDATE', 'DELETE') THEN
                        old_row := to_jsonb(OLD);
                    END IF;
                    IF TG_OP IN ('INSERT', 'UPDATE') THEN
                        new_row := to_jsonb(NEW);
                    END IF;

                    source_row := COALESCE(new_row, old_row);

                    IF TG_NARGS > 0 AND NULLIF(TG_ARGV[0], '') IS NOT NULL THEN
                        primary_key_columns := string_to_array(TG_ARGV[0], ',');
                        FOREACH primary_key_column IN ARRAY primary_key_columns
                        LOOP
                            record_key := record_key || jsonb_build_object(
                                primary_key_column,
                                source_row -> primary_key_column
                            );
                        END LOOP;
                    END IF;

                    IF record_key = '{}'::JSONB THEN
                        record_key := jsonb_build_object('row_hash', md5(source_row::TEXT));
                    END IF;

                    SELECT COALESCE(jsonb_agg(field_name ORDER BY field_name), '[]'::JSONB)
                    INTO changed_fields_json
                    FROM (
                        SELECT DISTINCT jsonb_object_keys(
                            COALESCE(old_row, '{}'::JSONB) || COALESCE(new_row, '{}'::JSONB)
                        ) AS field_name
                    ) fields
                    WHERE field_name NOT IN ('created_at', 'created_by', 'updated_at', 'updated_by')
                      AND old_row -> field_name IS DISTINCT FROM new_row -> field_name;

                    resolved_actor := LEFT(
                        COALESCE(
                            NULLIF(current_setting('praxis.actor_user_id', true), ''),
                            CASE
                                WHEN TG_OP = 'INSERT' THEN source_row ->> 'created_by'
                                ELSE source_row ->> 'updated_by'
                            END,
                            source_row ->> 'created_by',
                            current_user,
                            'SYSTEM'
                        ),
                        120
                    );
                    resolved_request_id := LEFT(
                        NULLIF(current_setting('praxis.request_id', true), ''),
                        120
                    );

                    INSERT INTO %s (
                        table_schema,
                        table_name,
                        record_id,
                        operation,
                        actor_user_id,
                        request_id,
                        changed_fields,
                        old_data,
                        new_data,
                        created_at,
                        created_by,
                        updated_at,
                        updated_by
                    ) VALUES (
                        TG_TABLE_SCHEMA,
                        TG_TABLE_NAME,
                        LEFT(record_key::TEXT, 1000),
                        TG_OP,
                        resolved_actor,
                        resolved_request_id,
                        changed_fields_json::TEXT,
                        %s(old_row)::TEXT,
                        %s(new_row)::TEXT,
                        CURRENT_TIMESTAMP,
                        resolved_actor,
                        CURRENT_TIMESTAMP,
                        resolved_actor
                    );

                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql
                """.formatted(functionName, historyTable, redactFunction, redactFunction);
    }

    private String createProtectHistoryFunction(String functionName) {
        return """
                CREATE OR REPLACE FUNCTION %s()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'data_change_history is append-only';
                END;
                $$ LANGUAGE plpgsql
                """.formatted(functionName);
    }

    private void installTableTriggers(
            Connection connection,
            TableReference table,
            String quote,
            String applyFunction,
            String captureFunction
    ) throws SQLException {
        String qualifiedTable = qualifiedName(table.schema(), table.name(), quote);
        String primaryKeys = String.join(",", loadPrimaryKeyColumns(connection, table));

        execute(connection, "DROP TRIGGER IF EXISTS trg_praxis_audit_columns ON " + qualifiedTable);
        execute(connection, """
                CREATE TRIGGER trg_praxis_audit_columns
                BEFORE INSERT OR UPDATE ON %s
                FOR EACH ROW
                EXECUTE FUNCTION %s()
                """.formatted(qualifiedTable, applyFunction));

        execute(connection, "DROP TRIGGER IF EXISTS trg_praxis_row_history ON " + qualifiedTable);
        execute(connection, """
                CREATE TRIGGER trg_praxis_row_history
                AFTER INSERT OR UPDATE OR DELETE ON %s
                FOR EACH ROW
                EXECUTE FUNCTION %s('%s')
                """.formatted(
                qualifiedTable,
                captureFunction,
                escapeSqlLiteral(primaryKeys)
        ));
    }

    private List<String> loadPrimaryKeyColumns(
            Connection connection,
            TableReference table
    ) throws SQLException {
        Map<Short, String> orderedColumns = new TreeMap<>();
        DatabaseMetaData metadata = connection.getMetaData();
        try (ResultSet resultSet = metadata.getPrimaryKeys(
                connection.getCatalog(),
                table.schema(),
                table.name()
        )) {
            while (resultSet.next()) {
                short keySequence = resultSet.getShort("KEY_SEQ");
                String columnName = resultSet.getString("COLUMN_NAME");
                if (columnName != null) {
                    orderedColumns.put(keySequence, columnName);
                }
            }
        }
        return new ArrayList<>(orderedColumns.values());
    }

    private String resolveCurrentSchema(Connection connection) throws SQLException {
        String schema = connection.getSchema();
        if (schema != null && !schema.isBlank()) {
            return schema;
        }

        try (PreparedStatement statement = connection.prepareStatement("SELECT current_schema()")) {
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getString(1);
                }
            }
        }
        throw new SQLException("Não foi possível identificar o schema atual para instalar a auditoria.");
    }

    private boolean isPostgreSql(Connection connection) throws SQLException {
        String productName = connection.getMetaData().getDatabaseProductName();
        return productName != null && productName.toLowerCase(Locale.ROOT).contains("postgresql");
    }

    private String resolveIdentifierQuote(Connection connection) throws SQLException {
        String quote = connection.getMetaData().getIdentifierQuoteString();
        if (quote == null || quote.isBlank()) {
            return "\"";
        }
        return quote.trim();
    }

    private String qualifiedName(String schema, String objectName, String quote) {
        return quoteIdentifier(schema, quote) + "." + quoteIdentifier(objectName, quote);
    }

    private String quoteIdentifier(String identifier, String quote) {
        return quote + identifier.replace(quote, quote + quote) + quote;
    }

    private String escapeSqlLiteral(String value) {
        return value.replace("'", "''");
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private record TableReference(String schema, String name) {
    }
}
