/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TalentMatchRouteImport } from './routes/talent-match'
import { Route as SuboperadoresRouteImport } from './routes/suboperadores'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ParticipacoesRouteImport } from './routes/participacoes'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JornadasRouteImport } from './routes/jornadas'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EnviarLinkRouteImport } from './routes/enviar-link'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CompetenciasRouteImport } from './routes/competencias'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentJourneysIndexRouteImport } from './routes/assessment-journeys/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SimulationsNewRouteImport } from './routes/simulations/new'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ParticipacoesOperacoesEmLoteRouteImport } from './routes/participacoes.operacoes-em-lote'
import { Route as ParticipacoesJornadaRouteImport } from './routes/participacoes.jornada'
import { Route as NovaValidadorRouteImport } from './routes/nova.validador'
import { Route as NovaRapidoRouteImport } from './routes/nova.rapido'
import { Route as NovaPreviaRouteImport } from './routes/nova.previa'
import { Route as NovaPilotoRouteImport } from './routes/nova.piloto'
import { Route as NovaPersonagemRouteImport } from './routes/nova.personagem'
import { Route as NovaObjetivoRouteImport } from './routes/nova.objetivo'
import { Route as NovaMapaRouteImport } from './routes/nova.mapa'
import { Route as NovaGupyRouteImport } from './routes/nova.gupy'
import { Route as NovaGovernancaRouteImport } from './routes/nova.governanca'
import { Route as NovaDialogoRouteImport } from './routes/nova.dialogo'
import { Route as NovaCompetenciasRouteImport } from './routes/nova.competencias'
import { Route as NovaBlueprintRouteImport } from './routes/nova.blueprint'
import { Route as NovaAvaliacoesRouteImport } from './routes/nova.avaliacoes'
import { Route as NovaAvaliacaoRouteImport } from './routes/nova.avaliacao'
import { Route as JornadaAttemptIdRouteImport } from './routes/jornada.$attemptId'
import { Route as IntegrationsGupyHomologacaoRouteImport } from './routes/integrations.gupy-homologacao'
import { Route as IntegrationsProviderRouteImport } from './routes/integrations.$provider'
import { Route as DocsIntegracaoApiPropriaRouteImport } from './routes/docs.integracao-api-propria'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ConfiguracoesPerfilRouteImport } from './routes/configuracoes.perfil'
import { Route as ConfiguracoesIntegracoesRouteImport } from './routes/configuracoes.integracoes'
import { Route as ConfiguracoesContaRouteImport } from './routes/configuracoes.conta'
import { Route as ConfiguracoesApiRouteImport } from './routes/configuracoes.api'
import { Route as CandidatoTokenRouteImport } from './routes/candidato.$token'
import { Route as CandidateLinksNewRouteImport } from './routes/candidate-links/new'
import { Route as AvaliacoesEspecialistaRouteImport } from './routes/avaliacoes.especialista'
import { Route as AssessmentJourneysNewRouteImport } from './routes/assessment-journeys/new'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin.feature-flags'
import { Route as AdminEmpresasIndexRouteImport } from './routes/admin.empresas.index'
import { Route as CandidatoTokenResultadoRouteImport } from './routes/candidato.$token.resultado'
import { Route as AdminEmpresasEmpresaIdRouteImport } from './routes/admin.empresas.$empresaId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentMatchRoute = TalentMatchRouteImport.update({
  id: '/talent-match',
  path: '/talent-match',
  getParentRoute: () => rootRouteImport,
} as any)
const SuboperadoresRoute = SuboperadoresRouteImport.update({
  id: '/suboperadores',
  path: '/suboperadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipacoesRoute = ParticipacoesRouteImport.update({
  id: '/participacoes',
  path: '/participacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadasRoute = JornadasRouteImport.update({
  id: '/jornadas',
  path: '/jornadas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarLinkRoute = EnviarLinkRouteImport.update({
  id: '/enviar-link',
  path: '/enviar-link',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciasRoute = CompetenciasRouteImport.update({
  id: '/competencias',
  path: '/competencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentJourneysIndexRoute = AssessmentJourneysIndexRouteImport.update({
  id: '/assessment-journeys/',
  path: '/assessment-journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsNewRoute = SimulationsNewRouteImport.update({
  id: '/simulations/new',
  path: '/simulations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/$attemptId',
  path: '/$attemptId',
  getParentRoute: () => ResultsRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipacoesOperacoesEmLoteRoute =
  ParticipacoesOperacoesEmLoteRouteImport.update({
    id: '/operacoes-em-lote',
    path: '/operacoes-em-lote',
    getParentRoute: () => ParticipacoesRoute,
  } as any)
const ParticipacoesJornadaRoute = ParticipacoesJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => ParticipacoesRoute,
} as any)
const NovaValidadorRoute = NovaValidadorRouteImport.update({
  id: '/nova/validador',
  path: '/nova/validador',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRapidoRoute = NovaRapidoRouteImport.update({
  id: '/nova/rapido',
  path: '/nova/rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPreviaRoute = NovaPreviaRouteImport.update({
  id: '/nova/previa',
  path: '/nova/previa',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPilotoRoute = NovaPilotoRouteImport.update({
  id: '/nova/piloto',
  path: '/nova/piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPersonagemRoute = NovaPersonagemRouteImport.update({
  id: '/nova/personagem',
  path: '/nova/personagem',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaObjetivoRoute = NovaObjetivoRouteImport.update({
  id: '/nova/objetivo',
  path: '/nova/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaMapaRoute = NovaMapaRouteImport.update({
  id: '/nova/mapa',
  path: '/nova/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaGupyRoute = NovaGupyRouteImport.update({
  id: '/nova/gupy',
  path: '/nova/gupy',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaGovernancaRoute = NovaGovernancaRouteImport.update({
  id: '/nova/governanca',
  path: '/nova/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaDialogoRoute = NovaDialogoRouteImport.update({
  id: '/nova/dialogo',
  path: '/nova/dialogo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaCompetenciasRoute = NovaCompetenciasRouteImport.update({
  id: '/nova/competencias',
  path: '/nova/competencias',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaBlueprintRoute = NovaBlueprintRouteImport.update({
  id: '/nova/blueprint',
  path: '/nova/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaAvaliacoesRoute = NovaAvaliacoesRouteImport.update({
  id: '/nova/avaliacoes',
  path: '/nova/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaAvaliacaoRoute = NovaAvaliacaoRouteImport.update({
  id: '/nova/avaliacao',
  path: '/nova/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaAttemptIdRoute = JornadaAttemptIdRouteImport.update({
  id: '/jornada/$attemptId',
  path: '/jornada/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGupyHomologacaoRoute =
  IntegrationsGupyHomologacaoRouteImport.update({
    id: '/gupy-homologacao',
    path: '/gupy-homologacao',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const IntegrationsProviderRoute = IntegrationsProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => IntegrationsRoute,
} as any)
const DocsIntegracaoApiPropriaRoute =
  DocsIntegracaoApiPropriaRouteImport.update({
    id: '/docs/integracao-api-propria',
    path: '/docs/integracao-api-propria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPerfilRoute = ConfiguracoesPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesIntegracoesRoute =
  ConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesContaRoute = ConfiguracoesContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesApiRoute = ConfiguracoesApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const CandidatoTokenRoute = CandidatoTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidateLinksNewRoute = CandidateLinksNewRouteImport.update({
  id: '/candidate-links/new',
  path: '/candidate-links/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesEspecialistaRoute = AvaliacoesEspecialistaRouteImport.update({
  id: '/especialista',
  path: '/especialista',
  getParentRoute: () => AvaliacoesRoute,
} as any)
const AssessmentJourneysNewRoute = AssessmentJourneysNewRouteImport.update({
  id: '/assessment-journeys/new',
  path: '/assessment-journeys/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/admin/empresas/',
  path: '/admin/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoTokenResultadoRoute = CandidatoTokenResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => CandidatoTokenRoute,
} as any)
const AdminEmpresasEmpresaIdRoute = AdminEmpresasEmpresaIdRouteImport.update({
  id: '/admin/empresas/$empresaId',
  path: '/admin/empresas/$empresaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/billing': typeof BillingRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/enviar-link': typeof EnviarLinkRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jornadas': typeof JornadasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/notifications': typeof NotificationsRoute
  '/parceiros': typeof ParceirosRoute
  '/participacoes': typeof ParticipacoesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/results': typeof ResultsRouteWithChildren
  '/suboperadores': typeof SuboperadoresRoute
  '/talent-match': typeof TalentMatchRoute
  '/team': typeof TeamRoute
  '/termos': typeof TermosRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/assessment-journeys/new': typeof AssessmentJourneysNewRoute
  '/avaliacoes/especialista': typeof AvaliacoesEspecialistaRoute
  '/candidate-links/new': typeof CandidateLinksNewRoute
  '/candidato/$token': typeof CandidatoTokenRouteWithChildren
  '/configuracoes/api': typeof ConfiguracoesApiRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/docs/integracao-api-propria': typeof DocsIntegracaoApiPropriaRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/integrations/gupy-homologacao': typeof IntegrationsGupyHomologacaoRoute
  '/jornada/$attemptId': typeof JornadaAttemptIdRoute
  '/nova/avaliacao': typeof NovaAvaliacaoRoute
  '/nova/avaliacoes': typeof NovaAvaliacoesRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/previa': typeof NovaPreviaRoute
  '/nova/rapido': typeof NovaRapidoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/participacoes/jornada': typeof ParticipacoesJornadaRoute
  '/participacoes/operacoes-em-lote': typeof ParticipacoesOperacoesEmLoteRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/simulations/new': typeof SimulationsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/assessment-journeys/': typeof AssessmentJourneysIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/candidato/$token/resultado': typeof CandidatoTokenResultadoRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/billing': typeof BillingRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/enviar-link': typeof EnviarLinkRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jornadas': typeof JornadasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/notifications': typeof NotificationsRoute
  '/parceiros': typeof ParceirosRoute
  '/participacoes': typeof ParticipacoesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/results': typeof ResultsRouteWithChildren
  '/suboperadores': typeof SuboperadoresRoute
  '/talent-match': typeof TalentMatchRoute
  '/team': typeof TeamRoute
  '/termos': typeof TermosRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/assessment-journeys/new': typeof AssessmentJourneysNewRoute
  '/avaliacoes/especialista': typeof AvaliacoesEspecialistaRoute
  '/candidate-links/new': typeof CandidateLinksNewRoute
  '/candidato/$token': typeof CandidatoTokenRouteWithChildren
  '/configuracoes/api': typeof ConfiguracoesApiRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/docs/integracao-api-propria': typeof DocsIntegracaoApiPropriaRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/integrations/gupy-homologacao': typeof IntegrationsGupyHomologacaoRoute
  '/jornada/$attemptId': typeof JornadaAttemptIdRoute
  '/nova/avaliacao': typeof NovaAvaliacaoRoute
  '/nova/avaliacoes': typeof NovaAvaliacoesRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/previa': typeof NovaPreviaRoute
  '/nova/rapido': typeof NovaRapidoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/participacoes/jornada': typeof ParticipacoesJornadaRoute
  '/participacoes/operacoes-em-lote': typeof ParticipacoesOperacoesEmLoteRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/simulations/new': typeof SimulationsNewRoute
  '/admin': typeof AdminIndexRoute
  '/assessment-journeys': typeof AssessmentJourneysIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/candidato/$token/resultado': typeof CandidatoTokenResultadoRoute
  '/admin/empresas': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRouteWithChildren
  '/billing': typeof BillingRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/enviar-link': typeof EnviarLinkRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jornadas': typeof JornadasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/notifications': typeof NotificationsRoute
  '/parceiros': typeof ParceirosRoute
  '/participacoes': typeof ParticipacoesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/results': typeof ResultsRouteWithChildren
  '/suboperadores': typeof SuboperadoresRoute
  '/talent-match': typeof TalentMatchRoute
  '/team': typeof TeamRoute
  '/termos': typeof TermosRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/assessment-journeys/new': typeof AssessmentJourneysNewRoute
  '/avaliacoes/especialista': typeof AvaliacoesEspecialistaRoute
  '/candidate-links/new': typeof CandidateLinksNewRoute
  '/candidato/$token': typeof CandidatoTokenRouteWithChildren
  '/configuracoes/api': typeof ConfiguracoesApiRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/docs/integracao-api-propria': typeof DocsIntegracaoApiPropriaRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/integrations/gupy-homologacao': typeof IntegrationsGupyHomologacaoRoute
  '/jornada/$attemptId': typeof JornadaAttemptIdRoute
  '/nova/avaliacao': typeof NovaAvaliacaoRoute
  '/nova/avaliacoes': typeof NovaAvaliacoesRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/previa': typeof NovaPreviaRoute
  '/nova/rapido': typeof NovaRapidoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/participacoes/jornada': typeof ParticipacoesJornadaRoute
  '/participacoes/operacoes-em-lote': typeof ParticipacoesOperacoesEmLoteRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/simulations/new': typeof SimulationsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/assessment-journeys/': typeof AssessmentJourneysIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/candidato/$token/resultado': typeof CandidatoTokenResultadoRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacoes'
    | '/billing'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/cookies'
    | '/dashboard'
    | '/enviar-link'
    | '/integrations'
    | '/jornadas'
    | '/login'
    | '/manual'
    | '/monitoramento'
    | '/notifications'
    | '/parceiros'
    | '/participacoes'
    | '/privacidade'
    | '/recuperar-senha'
    | '/results'
    | '/suboperadores'
    | '/talent-match'
    | '/team'
    | '/termos'
    | '/admin/feature-flags'
    | '/assessment-journeys/new'
    | '/avaliacoes/especialista'
    | '/candidate-links/new'
    | '/candidato/$token'
    | '/configuracoes/api'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/convite/$token'
    | '/docs/integracao-api-propria'
    | '/integrations/$provider'
    | '/integrations/gupy-homologacao'
    | '/jornada/$attemptId'
    | '/nova/avaliacao'
    | '/nova/avaliacoes'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/previa'
    | '/nova/rapido'
    | '/nova/validador'
    | '/participacoes/jornada'
    | '/participacoes/operacoes-em-lote'
    | '/reset-password/$token'
    | '/results/$attemptId'
    | '/simulations/new'
    | '/admin/'
    | '/assessment-journeys/'
    | '/admin/empresas/$empresaId'
    | '/candidato/$token/resultado'
    | '/admin/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacoes'
    | '/billing'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/cookies'
    | '/dashboard'
    | '/enviar-link'
    | '/integrations'
    | '/jornadas'
    | '/login'
    | '/manual'
    | '/monitoramento'
    | '/notifications'
    | '/parceiros'
    | '/participacoes'
    | '/privacidade'
    | '/recuperar-senha'
    | '/results'
    | '/suboperadores'
    | '/talent-match'
    | '/team'
    | '/termos'
    | '/admin/feature-flags'
    | '/assessment-journeys/new'
    | '/avaliacoes/especialista'
    | '/candidate-links/new'
    | '/candidato/$token'
    | '/configuracoes/api'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/convite/$token'
    | '/docs/integracao-api-propria'
    | '/integrations/$provider'
    | '/integrations/gupy-homologacao'
    | '/jornada/$attemptId'
    | '/nova/avaliacao'
    | '/nova/avaliacoes'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/previa'
    | '/nova/rapido'
    | '/nova/validador'
    | '/participacoes/jornada'
    | '/participacoes/operacoes-em-lote'
    | '/reset-password/$token'
    | '/results/$attemptId'
    | '/simulations/new'
    | '/admin'
    | '/assessment-journeys'
    | '/admin/empresas/$empresaId'
    | '/candidato/$token/resultado'
    | '/admin/empresas'
  id:
    | '__root__'
    | '/'
    | '/avaliacoes'
    | '/billing'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/cookies'
    | '/dashboard'
    | '/enviar-link'
    | '/integrations'
    | '/jornadas'
    | '/login'
    | '/manual'
    | '/monitoramento'
    | '/notifications'
    | '/parceiros'
    | '/participacoes'
    | '/privacidade'
    | '/recuperar-senha'
    | '/results'
    | '/suboperadores'
    | '/talent-match'
    | '/team'
    | '/termos'
    | '/admin/feature-flags'
    | '/assessment-journeys/new'
    | '/avaliacoes/especialista'
    | '/candidate-links/new'
    | '/candidato/$token'
    | '/configuracoes/api'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/convite/$token'
    | '/docs/integracao-api-propria'
    | '/integrations/$provider'
    | '/integrations/gupy-homologacao'
    | '/jornada/$attemptId'
    | '/nova/avaliacao'
    | '/nova/avaliacoes'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/previa'
    | '/nova/rapido'
    | '/nova/validador'
    | '/participacoes/jornada'
    | '/participacoes/operacoes-em-lote'
    | '/reset-password/$token'
    | '/results/$attemptId'
    | '/simulations/new'
    | '/admin/'
    | '/assessment-journeys/'
    | '/admin/empresas/$empresaId'
    | '/candidato/$token/resultado'
    | '/admin/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacoesRoute: typeof AvaliacoesRouteWithChildren
  BillingRoute: typeof BillingRoute
  CandidatoRoute: typeof CandidatoRouteWithChildren
  ComecarRoute: typeof ComecarRoute
  CompetenciasRoute: typeof CompetenciasRoute
  ComplianceRoute: typeof ComplianceRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  EnviarLinkRoute: typeof EnviarLinkRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  JornadasRoute: typeof JornadasRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  NotificationsRoute: typeof NotificationsRoute
  ParceirosRoute: typeof ParceirosRoute
  ParticipacoesRoute: typeof ParticipacoesRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  SuboperadoresRoute: typeof SuboperadoresRoute
  TalentMatchRoute: typeof TalentMatchRoute
  TeamRoute: typeof TeamRoute
  TermosRoute: typeof TermosRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AssessmentJourneysNewRoute: typeof AssessmentJourneysNewRoute
  CandidateLinksNewRoute: typeof CandidateLinksNewRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  DocsIntegracaoApiPropriaRoute: typeof DocsIntegracaoApiPropriaRoute
  JornadaAttemptIdRoute: typeof JornadaAttemptIdRoute
  NovaAvaliacaoRoute: typeof NovaAvaliacaoRoute
  NovaAvaliacoesRoute: typeof NovaAvaliacoesRoute
  NovaBlueprintRoute: typeof NovaBlueprintRoute
  NovaCompetenciasRoute: typeof NovaCompetenciasRoute
  NovaDialogoRoute: typeof NovaDialogoRoute
  NovaGovernancaRoute: typeof NovaGovernancaRoute
  NovaGupyRoute: typeof NovaGupyRoute
  NovaMapaRoute: typeof NovaMapaRoute
  NovaObjetivoRoute: typeof NovaObjetivoRoute
  NovaPersonagemRoute: typeof NovaPersonagemRoute
  NovaPilotoRoute: typeof NovaPilotoRoute
  NovaPreviaRoute: typeof NovaPreviaRoute
  NovaRapidoRoute: typeof NovaRapidoRoute
  NovaValidadorRoute: typeof NovaValidadorRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  SimulationsNewRoute: typeof SimulationsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AssessmentJourneysIndexRoute: typeof AssessmentJourneysIndexRoute
  AdminEmpresasEmpresaIdRoute: typeof AdminEmpresasEmpresaIdRoute
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-match': {
      id: '/talent-match'
      path: '/talent-match'
      fullPath: '/talent-match'
      preLoaderRoute: typeof TalentMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suboperadores': {
      id: '/suboperadores'
      path: '/suboperadores'
      fullPath: '/suboperadores'
      preLoaderRoute: typeof SuboperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participacoes': {
      id: '/participacoes'
      path: '/participacoes'
      fullPath: '/participacoes'
      preLoaderRoute: typeof ParticipacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornadas': {
      id: '/jornadas'
      path: '/jornadas'
      fullPath: '/jornadas'
      preLoaderRoute: typeof JornadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-link': {
      id: '/enviar-link'
      path: '/enviar-link'
      fullPath: '/enviar-link'
      preLoaderRoute: typeof EnviarLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencias': {
      id: '/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof CompetenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-journeys/': {
      id: '/assessment-journeys/'
      path: '/assessment-journeys'
      fullPath: '/assessment-journeys/'
      preLoaderRoute: typeof AssessmentJourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/new': {
      id: '/simulations/new'
      path: '/simulations/new'
      fullPath: '/simulations/new'
      preLoaderRoute: typeof SimulationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participacoes/operacoes-em-lote': {
      id: '/participacoes/operacoes-em-lote'
      path: '/operacoes-em-lote'
      fullPath: '/participacoes/operacoes-em-lote'
      preLoaderRoute: typeof ParticipacoesOperacoesEmLoteRouteImport
      parentRoute: typeof ParticipacoesRoute
    }
    '/participacoes/jornada': {
      id: '/participacoes/jornada'
      path: '/jornada'
      fullPath: '/participacoes/jornada'
      preLoaderRoute: typeof ParticipacoesJornadaRouteImport
      parentRoute: typeof ParticipacoesRoute
    }
    '/nova/validador': {
      id: '/nova/validador'
      path: '/nova/validador'
      fullPath: '/nova/validador'
      preLoaderRoute: typeof NovaValidadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/rapido': {
      id: '/nova/rapido'
      path: '/nova/rapido'
      fullPath: '/nova/rapido'
      preLoaderRoute: typeof NovaRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/previa': {
      id: '/nova/previa'
      path: '/nova/previa'
      fullPath: '/nova/previa'
      preLoaderRoute: typeof NovaPreviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/piloto': {
      id: '/nova/piloto'
      path: '/nova/piloto'
      fullPath: '/nova/piloto'
      preLoaderRoute: typeof NovaPilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/personagem': {
      id: '/nova/personagem'
      path: '/nova/personagem'
      fullPath: '/nova/personagem'
      preLoaderRoute: typeof NovaPersonagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/objetivo': {
      id: '/nova/objetivo'
      path: '/nova/objetivo'
      fullPath: '/nova/objetivo'
      preLoaderRoute: typeof NovaObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/mapa': {
      id: '/nova/mapa'
      path: '/nova/mapa'
      fullPath: '/nova/mapa'
      preLoaderRoute: typeof NovaMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/gupy': {
      id: '/nova/gupy'
      path: '/nova/gupy'
      fullPath: '/nova/gupy'
      preLoaderRoute: typeof NovaGupyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/governanca': {
      id: '/nova/governanca'
      path: '/nova/governanca'
      fullPath: '/nova/governanca'
      preLoaderRoute: typeof NovaGovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/dialogo': {
      id: '/nova/dialogo'
      path: '/nova/dialogo'
      fullPath: '/nova/dialogo'
      preLoaderRoute: typeof NovaDialogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/competencias': {
      id: '/nova/competencias'
      path: '/nova/competencias'
      fullPath: '/nova/competencias'
      preLoaderRoute: typeof NovaCompetenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/blueprint': {
      id: '/nova/blueprint'
      path: '/nova/blueprint'
      fullPath: '/nova/blueprint'
      preLoaderRoute: typeof NovaBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/avaliacoes': {
      id: '/nova/avaliacoes'
      path: '/nova/avaliacoes'
      fullPath: '/nova/avaliacoes'
      preLoaderRoute: typeof NovaAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/avaliacao': {
      id: '/nova/avaliacao'
      path: '/nova/avaliacao'
      fullPath: '/nova/avaliacao'
      preLoaderRoute: typeof NovaAvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada/$attemptId': {
      id: '/jornada/$attemptId'
      path: '/jornada/$attemptId'
      fullPath: '/jornada/$attemptId'
      preLoaderRoute: typeof JornadaAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/gupy-homologacao': {
      id: '/integrations/gupy-homologacao'
      path: '/gupy-homologacao'
      fullPath: '/integrations/gupy-homologacao'
      preLoaderRoute: typeof IntegrationsGupyHomologacaoRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/$provider': {
      id: '/integrations/$provider'
      path: '/$provider'
      fullPath: '/integrations/$provider'
      preLoaderRoute: typeof IntegrationsProviderRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/docs/integracao-api-propria': {
      id: '/docs/integracao-api-propria'
      path: '/docs/integracao-api-propria'
      fullPath: '/docs/integracao-api-propria'
      preLoaderRoute: typeof DocsIntegracaoApiPropriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/perfil': {
      id: '/configuracoes/perfil'
      path: '/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof ConfiguracoesPerfilRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/integracoes': {
      id: '/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof ConfiguracoesIntegracoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/conta': {
      id: '/configuracoes/conta'
      path: '/conta'
      fullPath: '/configuracoes/conta'
      preLoaderRoute: typeof ConfiguracoesContaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/api': {
      id: '/configuracoes/api'
      path: '/api'
      fullPath: '/configuracoes/api'
      preLoaderRoute: typeof ConfiguracoesApiRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/candidato/$token': {
      id: '/candidato/$token'
      path: '/$token'
      fullPath: '/candidato/$token'
      preLoaderRoute: typeof CandidatoTokenRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidate-links/new': {
      id: '/candidate-links/new'
      path: '/candidate-links/new'
      fullPath: '/candidate-links/new'
      preLoaderRoute: typeof CandidateLinksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/especialista': {
      id: '/avaliacoes/especialista'
      path: '/especialista'
      fullPath: '/avaliacoes/especialista'
      preLoaderRoute: typeof AvaliacoesEspecialistaRouteImport
      parentRoute: typeof AvaliacoesRoute
    }
    '/assessment-journeys/new': {
      id: '/assessment-journeys/new'
      path: '/assessment-journeys/new'
      fullPath: '/assessment-journeys/new'
      preLoaderRoute: typeof AssessmentJourneysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/': {
      id: '/admin/empresas/'
      path: '/admin/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/$token/resultado': {
      id: '/candidato/$token/resultado'
      path: '/resultado'
      fullPath: '/candidato/$token/resultado'
      preLoaderRoute: typeof CandidatoTokenResultadoRouteImport
      parentRoute: typeof CandidatoTokenRoute
    }
    '/admin/empresas/$empresaId': {
      id: '/admin/empresas/$empresaId'
      path: '/admin/empresas/$empresaId'
      fullPath: '/admin/empresas/$empresaId'
      preLoaderRoute: typeof AdminEmpresasEmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AvaliacoesRouteChildren {
  AvaliacoesEspecialistaRoute: typeof AvaliacoesEspecialistaRoute
}

const AvaliacoesRouteChildren: AvaliacoesRouteChildren = {
  AvaliacoesEspecialistaRoute: AvaliacoesEspecialistaRoute,
}

const AvaliacoesRouteWithChildren = AvaliacoesRoute._addFileChildren(
  AvaliacoesRouteChildren,
)

interface CandidatoTokenRouteChildren {
  CandidatoTokenResultadoRoute: typeof CandidatoTokenResultadoRoute
}

const CandidatoTokenRouteChildren: CandidatoTokenRouteChildren = {
  CandidatoTokenResultadoRoute: CandidatoTokenResultadoRoute,
}

const CandidatoTokenRouteWithChildren = CandidatoTokenRoute._addFileChildren(
  CandidatoTokenRouteChildren,
)

interface CandidatoRouteChildren {
  CandidatoTokenRoute: typeof CandidatoTokenRouteWithChildren
}

const CandidatoRouteChildren: CandidatoRouteChildren = {
  CandidatoTokenRoute: CandidatoTokenRouteWithChildren,
}

const CandidatoRouteWithChildren = CandidatoRoute._addFileChildren(
  CandidatoRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesApiRoute: typeof ConfiguracoesApiRoute
  ConfiguracoesContaRoute: typeof ConfiguracoesContaRoute
  ConfiguracoesIntegracoesRoute: typeof ConfiguracoesIntegracoesRoute
  ConfiguracoesPerfilRoute: typeof ConfiguracoesPerfilRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesApiRoute: ConfiguracoesApiRoute,
  ConfiguracoesContaRoute: ConfiguracoesContaRoute,
  ConfiguracoesIntegracoesRoute: ConfiguracoesIntegracoesRoute,
  ConfiguracoesPerfilRoute: ConfiguracoesPerfilRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsProviderRoute: typeof IntegrationsProviderRoute
  IntegrationsGupyHomologacaoRoute: typeof IntegrationsGupyHomologacaoRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsProviderRoute: IntegrationsProviderRoute,
  IntegrationsGupyHomologacaoRoute: IntegrationsGupyHomologacaoRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ParticipacoesRouteChildren {
  ParticipacoesJornadaRoute: typeof ParticipacoesJornadaRoute
  ParticipacoesOperacoesEmLoteRoute: typeof ParticipacoesOperacoesEmLoteRoute
}

const ParticipacoesRouteChildren: ParticipacoesRouteChildren = {
  ParticipacoesJornadaRoute: ParticipacoesJornadaRoute,
  ParticipacoesOperacoesEmLoteRoute: ParticipacoesOperacoesEmLoteRoute,
}

const ParticipacoesRouteWithChildren = ParticipacoesRoute._addFileChildren(
  ParticipacoesRouteChildren,
)

interface ResultsRouteChildren {
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacoesRoute: AvaliacoesRouteWithChildren,
  BillingRoute: BillingRoute,
  CandidatoRoute: CandidatoRouteWithChildren,
  ComecarRoute: ComecarRoute,
  CompetenciasRoute: CompetenciasRoute,
  ComplianceRoute: ComplianceRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  EnviarLinkRoute: EnviarLinkRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  JornadasRoute: JornadasRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  NotificationsRoute: NotificationsRoute,
  ParceirosRoute: ParceirosRoute,
  ParticipacoesRoute: ParticipacoesRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResultsRoute: ResultsRouteWithChildren,
  SuboperadoresRoute: SuboperadoresRoute,
  TalentMatchRoute: TalentMatchRoute,
  TeamRoute: TeamRoute,
  TermosRoute: TermosRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AssessmentJourneysNewRoute: AssessmentJourneysNewRoute,
  CandidateLinksNewRoute: CandidateLinksNewRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  DocsIntegracaoApiPropriaRoute: DocsIntegracaoApiPropriaRoute,
  JornadaAttemptIdRoute: JornadaAttemptIdRoute,
  NovaAvaliacaoRoute: NovaAvaliacaoRoute,
  NovaAvaliacoesRoute: NovaAvaliacoesRoute,
  NovaBlueprintRoute: NovaBlueprintRoute,
  NovaCompetenciasRoute: NovaCompetenciasRoute,
  NovaDialogoRoute: NovaDialogoRoute,
  NovaGovernancaRoute: NovaGovernancaRoute,
  NovaGupyRoute: NovaGupyRoute,
  NovaMapaRoute: NovaMapaRoute,
  NovaObjetivoRoute: NovaObjetivoRoute,
  NovaPersonagemRoute: NovaPersonagemRoute,
  NovaPilotoRoute: NovaPilotoRoute,
  NovaPreviaRoute: NovaPreviaRoute,
  NovaRapidoRoute: NovaRapidoRoute,
  NovaValidadorRoute: NovaValidadorRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  SimulationsNewRoute: SimulationsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AssessmentJourneysIndexRoute: AssessmentJourneysIndexRoute,
  AdminEmpresasEmpresaIdRoute: AdminEmpresasEmpresaIdRoute,
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
