/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentMatchRouteImport } from './routes/talent-match'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as EnviarLinkRouteImport } from './routes/enviar-link'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CompetenciasRouteImport } from './routes/competencias'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NovaValidadorRouteImport } from './routes/nova.validador'
import { Route as NovaPilotoRouteImport } from './routes/nova.piloto'
import { Route as NovaPersonagemRouteImport } from './routes/nova.personagem'
import { Route as NovaObjetivoRouteImport } from './routes/nova.objetivo'
import { Route as NovaMapaRouteImport } from './routes/nova.mapa'
import { Route as NovaGupyRouteImport } from './routes/nova.gupy'
import { Route as NovaGovernancaRouteImport } from './routes/nova.governanca'
import { Route as NovaDialogoRouteImport } from './routes/nova.dialogo'
import { Route as NovaCompetenciasRouteImport } from './routes/nova.competencias'
import { Route as NovaBlueprintRouteImport } from './routes/nova.blueprint'
import { Route as ConfiguracoesPerfilRouteImport } from './routes/configuracoes.perfil'
import { Route as ConfiguracoesIntegracoesRouteImport } from './routes/configuracoes.integracoes'
import { Route as ConfiguracoesContaRouteImport } from './routes/configuracoes.conta'
import { Route as CandidatoTokenRouteImport } from './routes/candidato.$token'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin.tenants.$tenantId'

const TalentMatchRoute = TalentMatchRouteImport.update({
  id: '/talent-match',
  path: '/talent-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarLinkRoute = EnviarLinkRouteImport.update({
  id: '/enviar-link',
  path: '/enviar-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciasRoute = CompetenciasRouteImport.update({
  id: '/competencias',
  path: '/competencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaValidadorRoute = NovaValidadorRouteImport.update({
  id: '/nova/validador',
  path: '/nova/validador',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPilotoRoute = NovaPilotoRouteImport.update({
  id: '/nova/piloto',
  path: '/nova/piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPersonagemRoute = NovaPersonagemRouteImport.update({
  id: '/nova/personagem',
  path: '/nova/personagem',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaObjetivoRoute = NovaObjetivoRouteImport.update({
  id: '/nova/objetivo',
  path: '/nova/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaMapaRoute = NovaMapaRouteImport.update({
  id: '/nova/mapa',
  path: '/nova/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaGupyRoute = NovaGupyRouteImport.update({
  id: '/nova/gupy',
  path: '/nova/gupy',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaGovernancaRoute = NovaGovernancaRouteImport.update({
  id: '/nova/governanca',
  path: '/nova/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaDialogoRoute = NovaDialogoRouteImport.update({
  id: '/nova/dialogo',
  path: '/nova/dialogo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaCompetenciasRoute = NovaCompetenciasRouteImport.update({
  id: '/nova/competencias',
  path: '/nova/competencias',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaBlueprintRoute = NovaBlueprintRouteImport.update({
  id: '/nova/blueprint',
  path: '/nova/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPerfilRoute = ConfiguracoesPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesIntegracoesRoute =
  ConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesContaRoute = ConfiguracoesContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const CandidatoTokenRoute = CandidatoTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => CandidatoRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/admin/tenants/$tenantId',
  path: '/admin/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/enviar-link': typeof EnviarLinkRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/talent-match': typeof TalentMatchRoute
  '/candidato/$token': typeof CandidatoTokenRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/enviar-link': typeof EnviarLinkRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/talent-match': typeof TalentMatchRoute
  '/candidato/$token': typeof CandidatoTokenRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/comecar': typeof ComecarRoute
  '/competencias': typeof CompetenciasRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/enviar-link': typeof EnviarLinkRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/talent-match': typeof TalentMatchRoute
  '/candidato/$token': typeof CandidatoTokenRoute
  '/configuracoes/conta': typeof ConfiguracoesContaRoute
  '/configuracoes/integracoes': typeof ConfiguracoesIntegracoesRoute
  '/configuracoes/perfil': typeof ConfiguracoesPerfilRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/competencias': typeof NovaCompetenciasRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/gupy': typeof NovaGupyRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/enviar-link'
    | '/monitoramento'
    | '/talent-match'
    | '/candidato/$token'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
    | '/admin/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/enviar-link'
    | '/monitoramento'
    | '/talent-match'
    | '/candidato/$token'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
    | '/admin'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/candidato'
    | '/comecar'
    | '/competencias'
    | '/compliance'
    | '/configuracoes'
    | '/enviar-link'
    | '/monitoramento'
    | '/talent-match'
    | '/candidato/$token'
    | '/configuracoes/conta'
    | '/configuracoes/integracoes'
    | '/configuracoes/perfil'
    | '/nova/blueprint'
    | '/nova/competencias'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/gupy'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
    | '/admin/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CandidatoRoute: typeof CandidatoRouteWithChildren
  ComecarRoute: typeof ComecarRoute
  CompetenciasRoute: typeof CompetenciasRoute
  ComplianceRoute: typeof ComplianceRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  EnviarLinkRoute: typeof EnviarLinkRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  TalentMatchRoute: typeof TalentMatchRoute
  NovaBlueprintRoute: typeof NovaBlueprintRoute
  NovaCompetenciasRoute: typeof NovaCompetenciasRoute
  NovaDialogoRoute: typeof NovaDialogoRoute
  NovaGovernancaRoute: typeof NovaGovernancaRoute
  NovaGupyRoute: typeof NovaGupyRoute
  NovaMapaRoute: typeof NovaMapaRoute
  NovaObjetivoRoute: typeof NovaObjetivoRoute
  NovaPersonagemRoute: typeof NovaPersonagemRoute
  NovaPilotoRoute: typeof NovaPilotoRoute
  NovaValidadorRoute: typeof NovaValidadorRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent-match': {
      id: '/talent-match'
      path: '/talent-match'
      fullPath: '/talent-match'
      preLoaderRoute: typeof TalentMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-link': {
      id: '/enviar-link'
      path: '/enviar-link'
      fullPath: '/enviar-link'
      preLoaderRoute: typeof EnviarLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencias': {
      id: '/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof CompetenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/validador': {
      id: '/nova/validador'
      path: '/nova/validador'
      fullPath: '/nova/validador'
      preLoaderRoute: typeof NovaValidadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/piloto': {
      id: '/nova/piloto'
      path: '/nova/piloto'
      fullPath: '/nova/piloto'
      preLoaderRoute: typeof NovaPilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/personagem': {
      id: '/nova/personagem'
      path: '/nova/personagem'
      fullPath: '/nova/personagem'
      preLoaderRoute: typeof NovaPersonagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/objetivo': {
      id: '/nova/objetivo'
      path: '/nova/objetivo'
      fullPath: '/nova/objetivo'
      preLoaderRoute: typeof NovaObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/mapa': {
      id: '/nova/mapa'
      path: '/nova/mapa'
      fullPath: '/nova/mapa'
      preLoaderRoute: typeof NovaMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/gupy': {
      id: '/nova/gupy'
      path: '/nova/gupy'
      fullPath: '/nova/gupy'
      preLoaderRoute: typeof NovaGupyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/governanca': {
      id: '/nova/governanca'
      path: '/nova/governanca'
      fullPath: '/nova/governanca'
      preLoaderRoute: typeof NovaGovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/dialogo': {
      id: '/nova/dialogo'
      path: '/nova/dialogo'
      fullPath: '/nova/dialogo'
      preLoaderRoute: typeof NovaDialogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/competencias': {
      id: '/nova/competencias'
      path: '/nova/competencias'
      fullPath: '/nova/competencias'
      preLoaderRoute: typeof NovaCompetenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/blueprint': {
      id: '/nova/blueprint'
      path: '/nova/blueprint'
      fullPath: '/nova/blueprint'
      preLoaderRoute: typeof NovaBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/perfil': {
      id: '/configuracoes/perfil'
      path: '/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof ConfiguracoesPerfilRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/integracoes': {
      id: '/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof ConfiguracoesIntegracoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/conta': {
      id: '/configuracoes/conta'
      path: '/conta'
      fullPath: '/configuracoes/conta'
      preLoaderRoute: typeof ConfiguracoesContaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/candidato/$token': {
      id: '/candidato/$token'
      path: '/$token'
      fullPath: '/candidato/$token'
      preLoaderRoute: typeof CandidatoTokenRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/admin/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidatoRouteChildren {
  CandidatoTokenRoute: typeof CandidatoTokenRoute
}

const CandidatoRouteChildren: CandidatoRouteChildren = {
  CandidatoTokenRoute: CandidatoTokenRoute,
}

const CandidatoRouteWithChildren = CandidatoRoute._addFileChildren(
  CandidatoRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesContaRoute: typeof ConfiguracoesContaRoute
  ConfiguracoesIntegracoesRoute: typeof ConfiguracoesIntegracoesRoute
  ConfiguracoesPerfilRoute: typeof ConfiguracoesPerfilRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesContaRoute: ConfiguracoesContaRoute,
  ConfiguracoesIntegracoesRoute: ConfiguracoesIntegracoesRoute,
  ConfiguracoesPerfilRoute: ConfiguracoesPerfilRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CandidatoRoute: CandidatoRouteWithChildren,
  ComecarRoute: ComecarRoute,
  CompetenciasRoute: CompetenciasRoute,
  ComplianceRoute: ComplianceRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  EnviarLinkRoute: EnviarLinkRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  TalentMatchRoute: TalentMatchRoute,
  NovaBlueprintRoute: NovaBlueprintRoute,
  NovaCompetenciasRoute: NovaCompetenciasRoute,
  NovaDialogoRoute: NovaDialogoRoute,
  NovaGovernancaRoute: NovaGovernancaRoute,
  NovaGupyRoute: NovaGupyRoute,
  NovaMapaRoute: NovaMapaRoute,
  NovaObjetivoRoute: NovaObjetivoRoute,
  NovaPersonagemRoute: NovaPersonagemRoute,
  NovaPilotoRoute: NovaPilotoRoute,
  NovaValidadorRoute: NovaValidadorRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
