/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovaValidadorRouteImport } from './routes/nova.validador'
import { Route as NovaPilotoRouteImport } from './routes/nova.piloto'
import { Route as NovaPersonagemRouteImport } from './routes/nova.personagem'
import { Route as NovaObjetivoRouteImport } from './routes/nova.objetivo'
import { Route as NovaMapaRouteImport } from './routes/nova.mapa'
import { Route as NovaGovernancaRouteImport } from './routes/nova.governanca'
import { Route as NovaDialogoRouteImport } from './routes/nova.dialogo'
import { Route as NovaBlueprintRouteImport } from './routes/nova.blueprint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaValidadorRoute = NovaValidadorRouteImport.update({
  id: '/nova/validador',
  path: '/nova/validador',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPilotoRoute = NovaPilotoRouteImport.update({
  id: '/nova/piloto',
  path: '/nova/piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPersonagemRoute = NovaPersonagemRouteImport.update({
  id: '/nova/personagem',
  path: '/nova/personagem',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaObjetivoRoute = NovaObjetivoRouteImport.update({
  id: '/nova/objetivo',
  path: '/nova/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaMapaRoute = NovaMapaRouteImport.update({
  id: '/nova/mapa',
  path: '/nova/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaGovernancaRoute = NovaGovernancaRouteImport.update({
  id: '/nova/governanca',
  path: '/nova/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaDialogoRoute = NovaDialogoRouteImport.update({
  id: '/nova/dialogo',
  path: '/nova/dialogo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaBlueprintRoute = NovaBlueprintRouteImport.update({
  id: '/nova/blueprint',
  path: '/nova/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nova/blueprint': typeof NovaBlueprintRoute
  '/nova/dialogo': typeof NovaDialogoRoute
  '/nova/governanca': typeof NovaGovernancaRoute
  '/nova/mapa': typeof NovaMapaRoute
  '/nova/objetivo': typeof NovaObjetivoRoute
  '/nova/personagem': typeof NovaPersonagemRoute
  '/nova/piloto': typeof NovaPilotoRoute
  '/nova/validador': typeof NovaValidadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nova/blueprint'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nova/blueprint'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
  id:
    | '__root__'
    | '/'
    | '/nova/blueprint'
    | '/nova/dialogo'
    | '/nova/governanca'
    | '/nova/mapa'
    | '/nova/objetivo'
    | '/nova/personagem'
    | '/nova/piloto'
    | '/nova/validador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovaBlueprintRoute: typeof NovaBlueprintRoute
  NovaDialogoRoute: typeof NovaDialogoRoute
  NovaGovernancaRoute: typeof NovaGovernancaRoute
  NovaMapaRoute: typeof NovaMapaRoute
  NovaObjetivoRoute: typeof NovaObjetivoRoute
  NovaPersonagemRoute: typeof NovaPersonagemRoute
  NovaPilotoRoute: typeof NovaPilotoRoute
  NovaValidadorRoute: typeof NovaValidadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/validador': {
      id: '/nova/validador'
      path: '/nova/validador'
      fullPath: '/nova/validador'
      preLoaderRoute: typeof NovaValidadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/piloto': {
      id: '/nova/piloto'
      path: '/nova/piloto'
      fullPath: '/nova/piloto'
      preLoaderRoute: typeof NovaPilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/personagem': {
      id: '/nova/personagem'
      path: '/nova/personagem'
      fullPath: '/nova/personagem'
      preLoaderRoute: typeof NovaPersonagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/objetivo': {
      id: '/nova/objetivo'
      path: '/nova/objetivo'
      fullPath: '/nova/objetivo'
      preLoaderRoute: typeof NovaObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/mapa': {
      id: '/nova/mapa'
      path: '/nova/mapa'
      fullPath: '/nova/mapa'
      preLoaderRoute: typeof NovaMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/governanca': {
      id: '/nova/governanca'
      path: '/nova/governanca'
      fullPath: '/nova/governanca'
      preLoaderRoute: typeof NovaGovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/dialogo': {
      id: '/nova/dialogo'
      path: '/nova/dialogo'
      fullPath: '/nova/dialogo'
      preLoaderRoute: typeof NovaDialogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova/blueprint': {
      id: '/nova/blueprint'
      path: '/nova/blueprint'
      fullPath: '/nova/blueprint'
      preLoaderRoute: typeof NovaBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovaBlueprintRoute: NovaBlueprintRoute,
  NovaDialogoRoute: NovaDialogoRoute,
  NovaGovernancaRoute: NovaGovernancaRoute,
  NovaMapaRoute: NovaMapaRoute,
  NovaObjetivoRoute: NovaObjetivoRoute,
  NovaPersonagemRoute: NovaPersonagemRoute,
  NovaPilotoRoute: NovaPilotoRoute,
  NovaValidadorRoute: NovaValidadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
