import type { ScreenManualDefinition } from "@/lib/screen-manuals";

export const SCREEN_MANUAL_OVERRIDES: ScreenManualDefinition[] = [
  {
    id: "jornadas-composicao",
    title: "Composição de jornadas",
    purpose: "Montar, ordenar, publicar e arquivar sequências de avaliações que serão aplicadas em conjunto.",
    flow: [
      "Crie ou selecione uma jornada.",
      "Adicione avaliações publicadas e organize a ordem de cada sequência.",
      "Publique a jornada e siga para Participações para gerar convites.",
    ],
    fields: [
      { name: "Nome", description: "Identificação interna do processo ou conjunto de avaliações." },
      { name: "Descrição", description: "Finalidade e contexto operacional da jornada." },
      { name: "Sequência", description: "Agrupamento que define quais etapas uma pessoa deverá executar e em qual ordem." },
      { name: "Obrigatória", description: "Indica se a avaliação precisa ser concluída para avançar na jornada." },
    ],
    permissions: ["Perfil EMPRESA com acesso à criação e gestão de jornadas."],
    states: ["Rascunho", "Publicada", "Arquivada"],
    blocks: [
      "Uma jornada sem avaliações não pode ser publicada.",
      "Somente avaliações publicadas podem ser adicionadas.",
      "Jornadas arquivadas não permitem alterações estruturais.",
    ],
    examples: ["Criar uma jornada de trainee com uma avaliação de atendimento seguida por liderança."],
    shortcuts: ["Organize todas as etapas antes de publicar.", "Use Participações para criar e acompanhar os convites."],
    matches: (pathname) => pathname === "/jornadas",
  },
  {
    id: "validador-diagnostico",
    title: "Validação estrutural",
    purpose: "Diagnosticar bloqueios, avisos, qualidade e prontidão da versão sem manter uma segunda interface de autoria.",
    flow: [
      "Abra o Validador a partir da avaliação ou selecione uma versão.",
      "Revise bloqueios e avisos calculados pelas regras de publicação.",
      "Use Corrigir no Diálogo para conteúdo e pontuação ou Abrir no Mapa para posição e conexões.",
      "Valide novamente e, quando estiver pronta, siga para Governança.",
    ],
    fields: [
      { name: "Prontidão", description: "Indica se a versão atende às regras estruturais mínimas para publicação." },
      { name: "Bloqueios", description: "Problemas obrigatórios que impedem a publicação." },
      { name: "Avisos", description: "Situações que exigem revisão, mas podem não impedir a publicação." },
      { name: "Qualidade", description: "Indicador consolidado calculado pelo backend para a versão." },
      { name: "Etapa", description: "Identificador do ponto do cenário relacionado ao diagnóstico." },
    ],
    permissions: ["Perfil EMPRESA com acesso à leitura da avaliação e aos editores responsáveis pela correção."],
    states: ["Carregando", "Sem problemas", "Com avisos", "Com bloqueios", "Pronta para Governança"],
    blocks: [
      "Avaliação ou versão não informada.",
      "Versão não encontrada ou pertencente a outra empresa.",
      "Bloqueios estruturais ainda ativos.",
      "Falha temporária ao calcular a validação.",
    ],
    examples: ["Identificar uma alternativa sem destino e abrir o Mapa para corrigir a conexão."],
    shortcuts: [
      "Use Validar novamente após salvar uma correção.",
      "O Validador não cria, edita nem exclui etapas ou alternativas.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/nova/validador",
  },
  {
    id: "participacoes",
    title: "Central de participações",
    purpose: "Centralizar participações individuais e por jornada, validade, andamento, cancelamento e acesso aos resultados.",
    flow: [
      "Crie uma participação individual ou um convite por jornada.",
      "Acompanhe o tipo, o processo, a situação e o progresso na mesma tabela.",
      "Copie, reenvie, amplie a validade ou cancele quando a ação estiver permitida.",
      "Abra o resultado quando uma participação individual estiver concluída.",
    ],
    fields: [
      { name: "Participante", description: "Nome e e-mail vinculados à participação." },
      { name: "Tipo", description: "Distingue participação individual de participação por jornada." },
      { name: "Processo", description: "Avaliação e versão ou jornada e sequência aplicadas." },
      { name: "Situação", description: "Aguardando início, em andamento, concluída, expirada ou cancelada." },
      { name: "Progresso", description: "Quantidade de etapas executadas e percentual estimado de conclusão." },
      { name: "Validade", description: "Condição do link e quantidade de dias restantes." },
    ],
    permissions: ["Perfil EMPRESA com acesso às participações e resultados da própria empresa."],
    states: [
      "Aguardando início",
      "Em andamento",
      "Sem atividade recente",
      "Concluída",
      "Expirada",
      "Cancelada",
    ],
    blocks: [
      "Avaliação ou jornada ainda não publicada.",
      "E-mail inválido.",
      "Créditos insuficientes para uma nova aplicação.",
      "Convite expirado para reenvio sem reativação.",
      "Participação concluída ou cancelada para novas ações.",
    ],
    examples: [
      "Localizar uma jornada, ampliar o convite em sete dias e reenviar sem criar outra participação.",
      "Cancelar um convite por jornada preservando o histórico já registrado.",
    ],
    shortcuts: [
      "Use os filtros de situação antes da busca por nome.",
      "A seleção de avaliação também encontra jornadas que contêm aquela avaliação.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/participacoes",
  },
  {
    id: "convite-jornada",
    title: "Convite por jornada",
    purpose: "Criar uma participação vinculada a uma jornada publicada e transferir sua gestão para Participações.",
    flow: [
      "Selecione a jornada publicada.",
      "Informe nome, e-mail e sequência aplicável.",
      "Crie a participação e copie o link gerado.",
      "Volte para Participações para acompanhar, reenviar, ampliar a validade ou cancelar.",
    ],
    fields: [
      { name: "Jornada", description: "Composição publicada disponibilizada à pessoa participante." },
      { name: "Nome", description: "Identificação da pessoa no processo." },
      { name: "E-mail", description: "Contato associado ao convite e à tentativa." },
      { name: "Sequência", description: "Conjunto de avaliações executado quando a jornada possui variações." },
      { name: "Validade", description: "O convite nasce com sete dias e pode ser ampliado na Central de Participações." },
    ],
    permissions: ["Perfil EMPRESA com acesso à jornada e à criação de participações."],
    states: ["Aguardando seleção", "Pronta para criar", "Criando", "Participação criada"],
    blocks: [
      "Nenhuma jornada publicada.",
      "Nome ou e-mail ausente.",
      "Sequência indisponível.",
      "Limite financeiro ou operacional atingido.",
    ],
    examples: ["Enviar a sequência principal da jornada de liderança para candidato@empresa.com."],
    shortcuts: [
      "Publique a jornada antes de abrir esta tela.",
      "Após criar, use Participações como única tela de gestão.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/participacoes/jornada",
  },
  {
    id: "central-operacional",
    title: "Central operacional",
    purpose: "Tratar somente exceções técnicas que exigem intervenção, como falhas de integração, retentativas e entregas em DLQ.",
    flow: [
      "Revise os indicadores de atenção.",
      "Abra o alerta, integração ou entrega com falha.",
      "Execute a correção, reprocesse quando permitido e confirme a mudança de estado.",
    ],
    fields: [
      { name: "Integrações com atenção", description: "Conexões pendentes ou com erro que precisam de diagnóstico." },
      { name: "Retentativas", description: "Entregas aguardando nova execução automática." },
      { name: "DLQ", description: "Falhas que esgotaram as tentativas automáticas e precisam de ação manual." },
      { name: "Alertas não lidos", description: "Eventos operacionais ainda não reconhecidos pelo usuário." },
    ],
    permissions: ["Perfil EMPRESA com responsabilidade operacional ou de integração."],
    states: ["Sem pendências", "Pendente", "Em retentativa", "Falha", "Resolvido"],
    blocks: ["Entrega ainda em processamento.", "Integração sem credencial válida.", "Item já resolvido ou reprocessado.", "Falha externa ainda ativa."],
    examples: ["Corrigir a credencial da integração e reprocessar uma entrega de resultado que chegou à DLQ."],
    shortcuts: ["Comece pelos itens em DLQ.", "Configurações permanentes devem ser alteradas na tela Integrações."],
    matches: (pathname) => pathname === "/monitoramento",
  },
  {
    id: "conformidade-contextual",
    title: "Conformidade contextual da versão",
    purpose: "Organizar os acessos às responsabilidades de conformidade sem manter uma lista, validação, auditoria ou privacidade concorrente.",
    flow: [
      "Abra a conformidade a partir de uma avaliação ou do Validador, com avaliação e versão informadas.",
      "Confira o resumo de prontidão e bloqueios.",
      "Abra o Validador para diagnóstico, Governança para publicação e auditoria ou Privacidade para LGPD.",
      "Retorne a Avaliações para alterar cadastro, versão ou situação.",
    ],
    fields: [
      { name: "Avaliação e versão", description: "Contexto obrigatório recebido da tela proprietária." },
      { name: "Prontidão", description: "Resumo somente leitura do resultado do Validador." },
      { name: "Bloqueios", description: "Quantidade de problemas estruturais ainda ativos." },
      { name: "Responsabilidade", description: "Indica qual tela mantém cada dado de conformidade." },
    ],
    permissions: ["Perfil EMPRESA com acesso à avaliação e às áreas de validação, governança ou privacidade."],
    states: ["Sem contexto", "Carregando", "Com bloqueios", "Estruturalmente aprovada"],
    blocks: [
      "Avaliação ou versão não informada.",
      "Versão não encontrada ou sem permissão.",
      "Falha ao calcular o resumo de validação.",
    ],
    examples: ["Abrir a conformidade da versão 3 e seguir para Governança para confirmar os termos de publicação."],
    shortcuts: [
      "Compliance não aparece mais como módulo independente no menu.",
      "Use os cartões para abrir diretamente a tela proprietária.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/compliance",
  },
  {
    id: "perfil-empresa",
    title: "Perfil da empresa",
    purpose: "Consultar e manter os dados cadastrais usados para identificar a empresa nas comunicações e integrações do Práxis.",
    flow: [
      "Revise os dados exibidos no cadastro empresarial.",
      "Selecione Editar dados para liberar o formulário.",
      "Atualize os campos necessários e selecione Salvar alterações.",
      "Confirme a mensagem de sucesso e revise os dados atualizados.",
    ],
    fields: [
      { name: "Nome fantasia", description: "Nome principal usado para identificar a empresa na interface." },
      { name: "Razão social", description: "Denominação jurídica cadastrada para a organização." },
      { name: "CNPJ", description: "Identificador fiscal da empresa." },
      { name: "E-mail corporativo", description: "Canal institucional usado em comunicações operacionais." },
      { name: "Telefone", description: "Contato corporativo da organização." },
      { name: "Site", description: "Endereço institucional iniciado por http:// ou https://." },
    ],
    permissions: ["Usuário autenticado com perfil EMPRESA da própria organização."],
    states: ["Carregando", "Consulta", "Editando", "Salvando", "Salvo", "Erro de validação"],
    blocks: [
      "Nome fantasia não informado.",
      "E-mail corporativo inválido.",
      "Site sem protocolo http:// ou https://.",
      "Sessão expirada ou usuário sem perfil EMPRESA.",
      "Empresa não encontrada no contexto autenticado.",
    ],
    examples: ["Atualizar o e-mail corporativo e o site institucional após uma mudança de domínio."],
    shortcuts: [
      "Use Cancelar para descartar alterações ainda não salvas.",
      "Todas as mudanças ficam registradas na auditoria.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/configuracoes/perfil",
  },
];

export function resolveScreenManualOverride(pathname: string) {
  return SCREEN_MANUAL_OVERRIDES.find((manual) => manual.matches(pathname));
}
