import type { ScreenManualDefinition } from "@/lib/screen-manuals";

export const SCREEN_MANUAL_OVERRIDES: ScreenManualDefinition[] = [
  {
    id: "editor-dialogo-multimidia",
    title: "Editor de diálogo e mídia acessível",
    purpose: "Criar etapas, alternativas e versões equivalentes de imagem, áudio e vídeo sem alterar silenciosamente o construto avaliado.",
    flow: ["Selecione a etapa.", "Anexe a mídia.", "Preencha texto equivalente e transcrição.", "Para vídeo, informe legenda WebVTT.", "Revise os bloqueios no Validador antes de publicar."],
    fields: [
      { name: "Mídia", description: "Imagem, áudio ou vídeo validado por MIME type e tamanho." },
      { name: "Texto equivalente", description: "Descrição que permite responder sem depender do formato visual ou sonoro." },
      { name: "Transcrição", description: "Conteúdo textual integral de áudio ou vídeo." },
      { name: "Legenda WebVTT", description: "Legenda sincronizada obrigatória para vídeo." },
      { name: "Versão da mídia", description: "Identificador imutável gravado na tentativa para auditoria e comparação." },
    ],
    permissions: ["Perfil EMPRESA ou especialista autorizado com permissão de editar rascunhos."],
    states: ["Sem mídia", "Enviando", "Mídia anexada", "Acessibilidade incompleta", "Pronta para validação", "Erro"],
    blocks: ["Versão publicada ou arquivada.", "Formato ou tamanho não permitido.", "URL sem HTTPS.", "Texto equivalente ausente.", "Áudio ou vídeo sem transcrição.", "Vídeo sem legenda WebVTT."],
    examples: ["Vídeo de atendimento com legenda, transcrição e versão textual equivalente.", "Áudio de cliente com transcrição integral e controles de velocidade."],
    shortcuts: ["Use Tab para alcançar os controles.", "Use Espaço para reproduzir ou pausar.", "Abra o Validador para ver todos os bloqueios.", "Consulte o processo completo na Central de manuais."],
    matches: (pathname) => pathname === "/nova/dialogo",
  },
  {
    id: "avaliacoes-catalogo",
    title: "Avaliações",
    purpose: "Centralizar o cadastro, as versões, a situação e as ações administrativas das avaliações usadas nas jornadas.",
    flow: [
      "Use a busca e o filtro para localizar uma avaliação.",
      "Abra a avaliação para revisar conteúdo, validação e publicação da versão selecionada.",
      "Use Duplicar para informar o nome de um novo rascunho independente.",
      "Use Arquivar, revise o impacto e confirme sem apagar histórico ou resultados.",
      "Adicione avaliações publicadas às jornadas e acompanhe aplicações em Participações.",
    ],
    fields: [
      { name: "Avaliação", description: "Nome, descrição, competências e data da última atualização." },
      { name: "Situação", description: "Indica se a versão atual está em rascunho, publicada ou arquivada." },
      { name: "Uso", description: "Quantidade de aplicações criadas e concluídas." },
      { name: "Nome da cópia", description: "Nome obrigatório, com até 180 caracteres, usado no novo rascunho independente." },
    ],
    permissions: [
      "Perfil EMPRESA pode criar, abrir, duplicar, arquivar e comparar avaliações.",
      "Especialista parceiro restrito pode criar, editar e revisar, sem duplicar, arquivar ou comparar.",
    ],
    states: ["Carregando", "Sem avaliações", "Rascunho", "Publicada", "Arquivada", "Duplicando", "Arquivando", "Erro"],
    blocks: [
      "Nome da nova avaliação não informado.",
      "Nome da nova avaliação acima de 180 caracteres.",
      "Avaliação já arquivada.",
      "Usuário sem permissão para duplicar ou arquivar.",
      "Falha ao carregar, duplicar ou arquivar a avaliação.",
    ],
    examples: [
      "Duplicar uma avaliação de atendimento para criar uma variação de suporte técnico sem alterar a original.",
      "Arquivar uma avaliação substituída preservando aplicações, resultados e auditoria.",
    ],
    shortcuts: [
      "A duplicação cria sempre um novo rascunho e não altera a origem.",
      "O arquivamento retira a avaliação de uso sem excluir o histórico.",
      "Use Jornadas para aplicar avaliações e Participações para acompanhar candidatos.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/avaliacoes",
  },
  {
    id: "jornadas-composicao",
    title: "Composição de jornadas",
    purpose: "Montar, ordenar, publicar e arquivar sequências de avaliações que serão aplicadas em conjunto.",
    flow: [
      "Crie ou selecione uma jornada.",
      "Adicione avaliações publicadas e organize a ordem de cada sequência.",
      "Publique a jornada e siga para Participações para gerar convites.",
    ],
    fields: [
      { name: "Nome", description: "Identificação interna do processo ou conjunto de avaliações." },
      { name: "Descrição", description: "Finalidade e contexto operacional da jornada." },
      { name: "Sequência", description: "Agrupamento que define quais etapas uma pessoa deverá executar e em qual ordem." },
      { name: "Obrigatória", description: "Indica se a avaliação precisa ser concluída para avançar na jornada." },
    ],
    permissions: ["Perfil EMPRESA com acesso à criação e gestão de jornadas."],
    states: ["Rascunho", "Publicada", "Arquivada"],
    blocks: [
      "Uma jornada sem avaliações não pode ser publicada.",
      "Somente avaliações publicadas podem ser adicionadas.",
      "Jornadas arquivadas não permitem alterações estruturais.",
    ],
    examples: ["Criar uma jornada de trainee com uma avaliação de atendimento seguida por liderança."],
    shortcuts: ["Organize todas as etapas antes de publicar.", "Use Participações para criar e acompanhar os convites."],
    matches: (pathname) => pathname === "/jornadas",
  },
  {
    id: "validador-diagnostico",
    title: "Validação estrutural",
    purpose: "Diagnosticar bloqueios, avisos, qualidade e prontidão da versão sem manter uma segunda interface de autoria.",
    flow: [
      "Abra o Validador a partir da avaliação ou selecione uma versão.",
      "Revise bloqueios e avisos calculados pelas regras de publicação.",
      "Use Corrigir no Diálogo para conteúdo e pontuação ou Abrir no Mapa para posição e conexões.",
      "Valide novamente e, quando estiver pronta, siga para Governança.",
    ],
    fields: [
      { name: "Prontidão", description: "Indica se a versão atende às regras estruturais mínimas para publicação." },
      { name: "Bloqueios", description: "Problemas obrigatórios que impedem a publicação." },
      { name: "Avisos", description: "Situações que exigem revisão, mas podem não impedir a publicação." },
      { name: "Qualidade", description: "Indicador consolidado calculado pelo backend para a versão." },
      { name: "Etapa", description: "Identificador do ponto do cenário relacionado ao diagnóstico." },
    ],
    permissions: ["Perfil EMPRESA com acesso à leitura da avaliação e aos editores responsáveis pela correção."],
    states: ["Carregando", "Sem problemas", "Com avisos", "Com bloqueios", "Pronta para Governança"],
    blocks: [
      "Avaliação ou versão não informada.",
      "Versão não encontrada ou pertencente a outra empresa.",
      "Bloqueios estruturais ainda ativos.",
      "Falha temporária ao calcular a validação.",
    ],
    examples: ["Identificar uma alternativa sem destino e abrir o Mapa para corrigir a conexão."],
    shortcuts: [
      "Use Validar novamente após salvar uma correção.",
      "O Validador não cria, edita nem exclui etapas ou alternativas.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/nova/validador",
  },
  {
    id: "participacoes",
    title: "Central de participações",
    purpose: "Centralizar participações individuais e por jornada, validade, andamento, cancelamento e acesso aos resultados.",
    flow: [
      "Crie uma participação individual ou um convite por jornada.",
      "Acompanhe o tipo, o processo, a situação e o progresso na mesma tabela.",
      "Copie, reenvie, amplie a validade ou cancele quando a ação estiver permitida.",
      "Abra o resultado quando uma participação individual estiver concluída.",
    ],
    fields: [
      { name: "Participante", description: "Nome e e-mail vinculados à participação." },
      { name: "Tipo", description: "Distingue participação individual de participação por jornada." },
      { name: "Processo", description: "Avaliação e versão ou jornada e sequência aplicadas." },
      { name: "Situação", description: "Aguardando início, em andamento, concluída, expirada ou cancelada." },
      { name: "Progresso", description: "Quantidade de etapas executadas e percentual estimado de conclusão." },
      { name: "Validade", description: "Condição do link e quantidade de dias restantes." },
    ],
    permissions: ["Perfil EMPRESA com acesso às participações e resultados da própria empresa."],
    states: [
      "Aguardando início",
      "Em andamento",
      "Sem atividade recente",
      "Concluída",
      "Expirada",
      "Cancelada",
    ],
    blocks: [
      "Avaliação ou jornada ainda não publicada.",
      "E-mail inválido.",
      "Créditos insuficientes para uma nova aplicação.",
      "Convite expirado para reenvio sem reativação.",
      "Participação concluída ou cancelada para novas ações.",
    ],
    examples: [
      "Localizar uma jornada, ampliar o convite em sete dias e reenviar sem criar outra participação.",
      "Cancelar um convite por jornada preservando o histórico já registrado.",
    ],
    shortcuts: [
      "Use os filtros de situação antes da busca por nome.",
      "A seleção de avaliação também encontra jornadas que contêm aquela avaliação.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/participacoes",
  },
  {
    id: "convite-jornada",
    title: "Convite por jornada",
    purpose: "Criar uma participação vinculada a uma jornada publicada e transferir sua gestão para Participações.",
    flow: [
      "Selecione a jornada publicada.",
      "Informe nome, e-mail e sequência aplicável.",
      "Crie a participação e copie o link gerado.",
      "Volte para Participações para acompanhar, reenviar, ampliar a validade ou cancelar.",
    ],
    fields: [
      { name: "Jornada", description: "Composição publicada disponibilizada à pessoa participante." },
      { name: "Nome", description: "Identificação da pessoa no processo." },
      { name: "E-mail", description: "Contato associado ao convite e à tentativa." },
      { name: "Sequência", description: "Conjunto de avaliações executado quando a jornada possui variações." },
      { name: "Validade", description: "O convite nasce com sete dias e pode ser ampliado na Central de Participações." },
    ],
    permissions: ["Perfil EMPRESA com acesso à jornada e à criação de participações."],
    states: ["Aguardando seleção", "Pronta para criar", "Criando", "Participação criada"],
    blocks: [
      "Nenhuma jornada publicada.",
      "Nome ou e-mail ausente.",
      "Sequência indisponível.",
      "Limite financeiro ou operacional atingido.",
    ],
    examples: ["Enviar a sequência principal da jornada de liderança para candidato@empresa.com."],
    shortcuts: [
      "Publique a jornada antes de abrir esta tela.",
      "Após criar, use Participações como única tela de gestão.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/participacoes/jornada",
  },
  {
    id: "central-operacional",
    title: "Central operacional",
    purpose: "Tratar somente exceções técnicas que exigem intervenção, como falhas de integração, retentativas e entregas em DLQ.",
    flow: [
      "Revise os indicadores de atenção.",
      "Abra o alerta, integração ou entrega com falha.",
      "Execute a correção, reprocesse quando permitido e confirme a mudança de estado.",
    ],
    fields: [
      { name: "Integrações com atenção", description: "Conexões pendentes ou com erro que precisam de diagnóstico." },
      { name: "Retentativas", description: "Entregas aguardando nova execução automática." },
      { name: "DLQ", description: "Falhas que esgotaram as tentativas automáticas e precisam de ação manual." },
      { name: "Alertas não lidos", description: "Eventos operacionais ainda não reconhecidos pelo usuário." },
    ],
    permissions: ["Perfil EMPRESA com responsabilidade operacional ou de integração."],
    states: ["Sem pendências", "Pendente", "Em retentativa", "Falha", "Resolvido"],
    blocks: ["Entrega ainda em processamento.", "Integração sem credencial válida.", "Item já resolvido ou reprocessado.", "Falha externa ainda ativa."],
    examples: ["Corrigir a credencial da integração e reprocessar uma entrega de resultado que chegou à DLQ."],
    shortcuts: ["Comece pelos itens em DLQ.", "Configurações permanentes devem ser alteradas na tela Integrações."],
    matches: (pathname) => pathname === "/monitoramento",
  },
  {
    id: "conformidade-contextual",
    title: "Conformidade contextual da versão",
    purpose: "Organizar os acessos às responsabilidades de conformidade sem manter uma lista, validação, auditoria ou privacidade concorrente.",
    flow: [
      "Abra a conformidade a partir de uma avaliação ou do Validador, com avaliação e versão informadas.",
      "Confira o resumo de prontidão e bloqueios.",
      "Abra o Validador para diagnóstico, Governança para publicação e auditoria ou Privacidade para LGPD.",
      "Retorne a Avaliações para alterar cadastro, versão ou situação.",
    ],
    fields: [
      { name: "Avaliação e versão", description: "Contexto obrigatório recebido da tela proprietária." },
      { name: "Prontidão", description: "Resumo somente leitura do resultado do Validador." },
      { name: "Bloqueios", description: "Quantidade de problemas estruturais ainda ativos." },
      { name: "Responsabilidade", description: "Indica qual tela mantém cada dado de conformidade." },
    ],
    permissions: ["Perfil EMPRESA com acesso à avaliação e às áreas de validação, governança ou privacidade."],
    states: ["Sem contexto", "Carregando", "Com bloqueios", "Estruturalmente aprovada"],
    blocks: [
      "Avaliação ou versão não informada.",
      "Versão não encontrada ou sem permissão.",
      "Falha ao calcular o resumo de validação.",
    ],
    examples: ["Abrir a conformidade da versão 3 e seguir para Governança para confirmar os termos de publicação."],
    shortcuts: [
      "Compliance não aparece mais como módulo independente no menu.",
      "Use os cartões para abrir diretamente a tela proprietária.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/compliance",
  },
  {
    id: "perfil-empresa",
    title: "Perfil da empresa",
    purpose: "Consultar e manter os dados cadastrais usados para identificar a empresa nas comunicações e integrações do Práxis.",
    flow: [
      "Revise os dados exibidos no cadastro empresarial.",
      "Selecione Editar dados para liberar o formulário.",
      "Atualize os campos necessários e selecione Salvar alterações.",
      "Confirme a mensagem de sucesso e revise os dados atualizados.",
    ],
    fields: [
      { name: "Nome fantasia", description: "Nome principal usado para identificar a empresa na interface." },
      { name: "Razão social", description: "Denominação jurídica cadastrada para a organização." },
      { name: "CNPJ", description: "Identificador fiscal da empresa." },
      { name: "E-mail corporativo", description: "Canal institucional usado em comunicações operacionais." },
      { name: "Telefone", description: "Contato corporativo da organização." },
      { name: "Site", description: "Endereço institucional iniciado por http:// ou https://." },
    ],
    permissions: ["Usuário autenticado com perfil EMPRESA da própria organização."],
    states: ["Carregando", "Consulta", "Editando", "Salvando", "Salvo", "Erro de validação"],
    blocks: [
      "Nome fantasia não informado.",
      "E-mail corporativo inválido.",
      "Site sem protocolo http:// ou https://.",
      "Sessão expirada ou usuário sem perfil EMPRESA.",
      "Empresa não encontrada no contexto autenticado.",
    ],
    examples: ["Atualizar o e-mail corporativo e o site institucional após uma mudança de domínio."],
    shortcuts: [
      "Use Cancelar para descartar alterações ainda não salvas.",
      "Todas as mudanças ficam registradas na auditoria.",
      "Consulte o processo completo na Central de manuais.",
    ],
    matches: (pathname) => pathname === "/configuracoes/perfil",
  },
  {
    id: "feature-flags",
    title: "Feature flags e rollout progressivo",
    purpose: "Controlar liberações graduais por contexto, reduzir risco operacional e interromper recursos críticos sem novo deploy.",
    flow: [
      "Crie a flag informando chave, finalidade, responsável, padrão seguro e prazo de remoção quando temporária.",
      "Defina os escopos explícitos por empresa, ambiente, plano, usuário ou papel e, quando necessário, um percentual de rollout.",
      "Use Simular para confirmar a variante estável que será entregue a um identificador antes de ativar.",
      "Ative a flag para iniciar a avaliação dos escopos e acompanhe métricas por variante.",
      "Acione Bloquear para interromper imediatamente o recurso e libere o kill switch somente após resolver o risco.",
      "Remova flags expiradas conforme o plano registrado e preserve o histórico de auditoria.",
    ],
    fields: [
      { name: "Chave", description: "Identificador técnico minúsculo e estável, sem dados pessoais ou segredos." },
      { name: "Descrição", description: "Objetivo operacional e comportamento liberado pela flag." },
      { name: "Responsável", description: "Pessoa ou equipe accountable pela decisão, observação e remoção." },
      { name: "Padrão ligado", description: "Valor seguro aplicado quando nenhum escopo ou override decidir a variante." },
      { name: "Override global", description: "Força ON ou OFF depois dos escopos e do rollout, ou mantém o padrão." },
      { name: "Rollout percentual", description: "Percentual de 0 a 100 calculado por hash estável do identificador." },
      { name: "Escopos", description: "Listas de empresas, ambientes, planos, usuários e papéis liberados explicitamente." },
      { name: "Exposta ao frontend", description: "Permite retornar somente o valor booleano avaliado, sem revelar regras internas." },
      { name: "Expiração", description: "Data obrigatória para flag temporária, acompanhada do plano de remoção." },
    ],
    permissions: [
      "Somente perfil ADMIN pode criar, editar, ativar, desativar, simular ou acionar kill switch.",
      "Usuários autenticados recebem apenas flags marcadas para frontend e já avaliadas no próprio contexto.",
    ],
    states: ["Inativa", "Ativa", "Bloqueada por kill switch", "Expirada", "Salvando", "Erro"],
    blocks: [
      "Chave, descrição ou responsável ausente.",
      "Rollout fora do intervalo de 0 a 100.",
      "Flag temporária sem expiração ou plano de remoção.",
      "Tentativa de alterar pontuação, gabarito ou tratamento de avaliação publicada.",
      "Usuário sem perfil ADMIN.",
      "Chave já utilizada por outra flag.",
    ],
    examples: [
      "Liberar um novo painel para duas empresas piloto e depois ampliar de 10% para 50% mantendo o mesmo bucket por usuário.",
      "Acionar o kill switch após aumento de falhas de integração, sem aguardar novo deploy.",
    ],
    shortcuts: [
      "Use Simular antes de ativar para validar empresa e identificador estável.",
      "Escopos explícitos têm precedência sobre rollout percentual.",
      "O kill switch sempre vence os demais escopos.",
      "Consulte a auditoria para identificar autor, alteração e horário.",
    ],
    matches: (pathname) => pathname === "/admin/feature-flags",
  },
  {
    id: "participacoes-operacoes-em-lote",
    title: "Operações em lote de participações",
    purpose: "Reutilizar filtros, organizar participações com tags e executar ações operacionais em escala com confirmação, idempotência e rastreabilidade item a item.",
    flow: [
      "Aplique filtros ou escolha uma visão salva privada ou compartilhada.",
      "Selecione os itens da página ou escolha todos os resultados do filtro atual.",
      "Escolha a ação, preencha os campos exigidos e selecione Revisar impacto.",
      "Confira quantidade, exceções, impacto e justificativa antes de confirmar.",
      "Acompanhe o progresso assíncrono e baixe o relatório final com sucesso, ignorado e falha.",
    ],
    fields: [
      { name: "Visão salva", description: "Conjunto reutilizável de filtros, ordenação e colunas, privado ou compartilhado com a empresa." },
      { name: "Filtros", description: "Avaliação, participante, situação do processo, situação do link e necessidade de atenção." },
      { name: "Seleção", description: "Distingue os itens marcados na página de todos os resultados do filtro confirmado." },
      { name: "Ação", description: "Reenvio, extensão, cancelamento de jornada, inclusão ou remoção de tag e exportação." },
      { name: "Dias adicionais", description: "Quantidade entre 1 e 365 aplicada somente à extensão de validade." },
      { name: "Tag", description: "Classificação interna com nome, cor e descrição, isolada por empresa." },
      { name: "Justificativa", description: "Contexto auditável, obrigatório para cancelamentos em lote." },
      { name: "Lote", description: "Job idempotente com progresso, contadores e resultado individual por participação." },
    ],
    permissions: [
      "Perfis EMPRESA, TEAM_MANAGER e OPERATIONS_MANAGER podem operar participações da própria empresa.",
      "A tela não oferece decisão de contratação em lote nem acesso a participações de outra empresa.",
    ],
    states: ["Sem seleção", "Pronto para revisar", "Prévia calculada", "Pendente", "Processando", "Concluído", "Concluído com falhas", "Falhou"],
    blocks: [
      "Nenhuma participação selecionada ou nenhum resultado no filtro.",
      "Item incompatível com a ação no estado atual.",
      "Cancelamento sem justificativa.",
      "Extensão fora do intervalo de 1 a 365 dias.",
      "Tag não informada ou pertencente a outra empresa.",
      "Limite de 500 itens explícitos ou 5.000 itens filtrados excedido.",
    ],
    examples: [
      "Selecionar todos os convites expirados de uma avaliação, estender por sete dias e acompanhar o resultado por item.",
      "Aplicar a tag Piloto Gupy a todas as participações do filtro sem alterar pontuação ou decisão humana.",
    ],
    shortcuts: [
      "Salve filtros recorrentes como visão compartilhada para o time.",
      "Use Selecionar página para um recorte manual e Todos do filtro para operações amplas.",
      "A seleção é congelada antes do processamento; alterações posteriores no filtro não mudam o lote.",
      "Use o relatório CSV como link para o processo completo de conferência e reconciliação do lote.",
    ],
    matches: (pathname) => pathname === "/participacoes/operacoes-em-lote",
  },
];

export function resolveScreenManualOverride(pathname: string) {
  return SCREEN_MANUAL_OVERRIDES.find((manual) => manual.matches(pathname));
}
